### ISSUE TITLE
Raspbian sources incomplete (and no mirror)

### ISSUE THREAD

**Issue by macmpi** [volumio/Build#102]
Hi,
While I was willing to install `python-rpi.gpio` (to implement button shutdown), I noted `apt-get install` would not make it available.
Looking at `/etc/apt/sources.list`, it seems we'd rather use std definition, as in std Jessie images:
```
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi
```
Shall we fix it [in here](https://github.com/volumio/Build/blob/master/volumio/etc/apt/sources.list)?
This would also allow use of proper mirroring according to users' regions.
Thanks.

**Comment by volumio** [comment]
Yes, we should. Thanks for reporting

**Comment by macmpi** [comment]
You're welcome.
Unsure the deb-src is really necessary in normal use though, may comment/remove it.

**Comment by volumio** [comment]
It's good to have, if people want to build stuff

**Comment by macmpi** [comment]
thing is, even with that change (followed by `sudo apt-get update`), I can not install `python-rpi.gpio`
```
volumio@volumio:~$ sudo apt-get install python-rpi.gpio
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-rpi.gpio
E: Couldn't find any package by regex 'python-rpi.gpio'
```
Package is present in `http://archive.raspberrypi.org/debian/ jessie/main armhf Packages`, and is found on Jessie lite using same `/etc/apt/sources.list` ...weird.

**Comment by macmpi** [comment]
Ok, so, in addition to updating `/etc/apt/sources.list`, one need to add the following `/etc/apt/sources.list.d/raspi.list`, containing the following:
```
deb http://archive.raspberrypi.org/debian/ jessie main ui
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.org/debian/ jessie main ui
```
(unsure what the existing empty `/etc/apt/sources.list.d/multistrap-debian.list` is meant for.

In addition, **key** for archive.raspberrypi.org/debian/ jessie should be added to keyring... (unsure this [hint](https://github.com/debian-pi/raspbian-ua-netinst/issues/64) may help for that).

With that, additional packages (like `python-rpi.gpio` are found and install fine).

**Comment by macmpi** [comment]
BTW, maybe some other things to look at, `apt-get install` spitting some warnings (locale settings, and apt-utils):
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "fr_FR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
debconf: delaying package configuration, since apt-utils is not installed
```

**Comment by macmpi** [comment]
Maybe the locale thing is fixed with newer build, as per https://github.com/volumio/Build/pull/97 ?

**Comment by macmpi** [comment]
Fixed as per https://github.com/volumio/Build/pull/116
