### ISSUE TITLE
Raspberry: streamlining /etc/modules

### ISSUE THREAD

**Issue by macmpi** [volumio/Build#103]
`i2c-bcm2708` is already loaded via device tree through `dtparam=i2c_arm=on` in `config.txt`. Therefore `i2c-bcm2708` in `/etc/modules` [in here](https://github.com/volumio/Build/blob/master/scripts/raspberryconfig.sh#L31) tries to load it twice [which may cause problems](https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=130549).
So, unless I'm missing something, I guess it should be removed from `/etc/modules`.

Similarly, use of `snd_bcm2835` in `/etc/modules` is deprecated and no longer [supported on 4.4 kernel](https://www.raspberrypi.org/forums/viewtopic.php?p=899919#p899919).
`dtparam=audio` is the default setting in `config.txt` in raspbian images, which Volumio2 uses.
So we can safely remove `snd_bcm2835` from `/etc/modules` too.

Only would remain `i2c-dev` that is required for address-based DAC detection.

Makes sense?

**Comment by volumio** [comment]
Yes let me test it and I'll merge the PR

**Comment by macmpi** [comment]
Did you find any issue with this?

**Comment by volumio** [comment]
No sorry I just forgot... Merged now
