### ISSUE TITLE
BBB Support

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Build#105]
Is there any Volumio 2 beta image for the BeagleBone Black?

**Comment by volumio** [comment]
Not yet unfortunately...
We were talking about it here:
http://www.diyaudio.com/forums/twisted-pear/258254-support-botic-linux-driver.html

**Comment by codewarriorFX** [comment]
Saw it, I can try setup a debian VM and build the bbb image.

"./build.sh -b arm -d bbb -v 2.001"
