### ISSUE TITLE
Support preallocated swap areas

### ISSUE THREAD

**Issue by earlchew** [volumio/Build#128]
If a swap partition is required, I want any dynamically created swap files to be used as a last resort, so that any pre-allocated swap areas (in particular swap partitions) have priority ahead of the dynamically created swap file.

For my configuration, I want to minimise the write activity on the root file system (by using a swap partition) in order to improve the robustness of the file system and improve boot times by reducing file system recovery time when the root file system is dirty.

**Comment by volumio** [comment]
Don't get it... We use only one preallocated swap file, in case we have less than 512 MB of RAM...

**Comment by earlchew** [comment]
See https://github.com/volumio/Build/pull/129

**Comment by earlchew** [comment]
@volumio I have a pre-allocated swap partition in my deployment.
