### ISSUE TITLE
missing package

### ISSUE THREAD

**Issue by balbuze** [volumio/Build#14]
I think it could be useful to add raspi-config. There is some feature useful.
I did it like that :
wget http://archive.raspberrypi.org/debian/pool/main/r/raspi-config/raspi-config_20151019_all.deb
apt-get install libnewt0.52 whiptail parted triggerhappy lua5.1
dpkg -i raspi-config_20151019_all.deb

**Comment by volumio** [comment]
Done! 
https://github.com/volumio/Build/commit/edc74c813c5ae9748c0315553755d4e1029db823
