### ISSUE TITLE
Update to upmpdcli 1.2.x

### ISSUE THREAD

**Issue by distler** [volumio/Build#142]
This will provide OpenHome support for streaming services (Tidal, Qobuz, ...).

**Comment by volumio** [comment]
Good hint, we'll do it!

**Comment by distler** [comment]
I see you have your own fork, instead of using the "standard" `upmpdcli` distribution.
Does that mean I *shouldn't* try to `apt-get upgrade upmpdcli` myself, but rather wait for your port?

**Comment by volumio** [comment]
Done!
