### ISSUE TITLE
OrangePiZero (One)

### ISSUE THREAD

**Issue by thanhvo31** [volumio/Build#155]

**Comment by thanhvo31** [comment]
solve by update build.

**Comment by thanhvo31** [comment]
Another issue:

trip:build/armv7/root/usr/sbin/start-statd: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/rtcwake'
strip:build/armv7/root/usr/sbin/locale-gen: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/zic'
strip:build/armv7/root/usr/sbin/samba_kcc: File format not recognized
strip:build/armv7/root/usr/sbin/pam-auth-update: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/cifs.upcall'
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/hostapd_cli'
strip:build/armv7/root/usr/sbin/samba_upgradedns: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/useradd'
strip:build/armv7/root/usr/sbin/tzconfig: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/rfkill'
strip:build/armv7/root/usr/sbin/policy-rc.d: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/chroot'
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/pwconv'
strip:build/armv7/root/usr/sbin/add-shell: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/groupmod'
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/nfsstat'
strip:build/armv7/root/usr/sbin/pam_getenv: File format not recognized
strip: Unable to recognise the format of the input file `build/armv7/root/usr/sbin/pwunconv'
strip:build/armv7/root/usr/sbin/update-inetd: File format not recognized
strip:build/armv7/root/usr/sbin/adduser: File format not recognized
Size after strip565M build/armv7/root/

**Comment by gkkpch** [comment]
Hi Than,
as promised, will send more info during the weekend. I think with an updated uenv.txt we should get the H3 board booting probably, good that you have uart.

**Comment by gkkpch** [comment]
These are ok. Nothing to worry about..

----- Reply message -----

**Comment by thanhvo31** [comment]
Hi Gé,

Any progress?
