### ISSUE TITLE
mpd.conf still contains filesystem_charset		"ISO-8859-1"

### ISSUE THREAD

**Issue by balbuze** [volumio/Build#17]
Even with the patch, after building mpd.conf is not set tu UTF-8. I think it's because mpd is updated during the build AFTER the mpd.conf is applied.

**Comment by balbuze** [comment]
maybe we could remove mpd as package each time it appears in the /recipes/xx.conf ? as the custom mpd is installed later ?

**Comment by balbuze** [comment]
well, I have removed mpd from /recipes/xx;conf but it's bad idea.. There is plenty of package depending of mpd and now they are missing.... back to the beginning...

**Comment by balbuze** [comment]
Don't understand why, but with my last build it's ok now....

**Comment by volumio** [comment]
This part gets done with the -b command, probably you've redone it
