### ISSUE TITLE
No uInitrd on bpipro build

### ISSUE THREAD

**Issue by 5685C4A059D5** [volumio/Build#208]
Tried generating a bpipro image with build.sh
The generated image, when flashed, is missing uInitrd in its boot partition. Volumio thus cannot boot (kernel panic: missing init).

The image was built on a Debian 8.8 VM, all tools in "Requirements" installed.

**Comment by gkkpch** [comment]
you will need to supply at least a log file from the build process, anything else is guess-work. I also need to see the contents from the boot folder down from the flashed image.

**Comment by 5685C4A059D5** [comment]
BOOT partition:

- boot_rd.cmd  
- bpipro_spd_i2c.bin  
- bpistd.bin  
- u-boot-sunxi-with-spl.bin
- boot.scr     
- bpipro_spd_i2c.fex  script.bin  
- uImage

As for build log, how do I make one? Tried simple ./build.sh > log but that didn't write everything.

**Comment by gkkpch** [comment]
Well, that is the only way to do it.You must use sudo, unless you are running as root.
(sudo) ./build.sh -b armv7 -d bpipro -v -something > build.log

Without the log I can't help any further...

**Comment by 5685C4A059D5** [comment]
Here is the log file (written by script)
[log.txt](https://github.com/volumio/Build/files/1091487/log.txt)

**Comment by gkkpch** [comment]
ok, it completely fails on copying the platform files and does not call the config script either, hence an invalid image (more than just uInitrd missing). Problem is, the scripts were created by someone who's obviously not maintaining it. I'll give it a go to see where exactly, but no promise to be able solve it.
I can't test as I don't have a banana pro..

**Comment by gkkpch** [comment]
to be expected, the bpiproimage.sh scripts has not been maintained and missed out on a vital change re. variable arm/ armv7 configuration.
It has been fixed a few minutes ago, you need to pull bpiproimage.sh from the repo.
You've built the armv7 rootfs succesfully, so there is no need to repeat that.
Just use `./build -d bpipro -v 2`

**Comment by gkkpch** [comment]
no feedback?

**Comment by 5685C4A059D5** [comment]
Unfortunately my bpi is broken.
I was able to run it once before then, ran into another issue, but couldn't read the output from the serial console. But at least the kernel and initrd loaded.

**Comment by gkkpch** [comment]
this can be closed
