### ISSUE TITLE
[Volumionext] Hifiberry Digi+ Pro digital out (TOSLink and COAX) shutoff when nothing is playing 

### ISSUE THREAD

**Issue by leafy7382** [volumio/Build#214]
When nothing is playing, the toslink gets shutoff, which is contrary to what the driver parameter is saying (refer to https://support.hifiberry.com/hc/en-us/community/posts/201491962-Toslink-light-don-039-t-turn-off?page=1#community_comment_115001631429). Is there anyway to respect the driver parameter? Having the TOSLINK/COAX output always on will help me a lot with my DAC which clicks a relay when it detects a change in the incoming signal (on/off, SR changes)

**Comment by leafy7382** [comment]
One needs to put this into the end of /boot/cmdline.txt
`snd-soc-core.pmdown_time=-1`

**Comment by volumio** [comment]
Is there a dtparam for this?

**Comment by leafy7382** [comment]
I don't think so at this moment, it's only set here https://github.com/raspberrypi/linux/blob/3aafce2a8bf59f03056253f22c3d19709ff5b7a6/sound/soc/soc-core.c

**Comment by leafy7382** [comment]
I was told that this would work too. Put the following line in  /etc/modprobe.d/snd-soc-core.conf 
options snd-soc-core pmdown_time=-1
