### ISSUE TITLE
[VolumioNext] USB noise within starting 15 secs of a track

### ISSUE THREAD

**Issue by leafy7382** [volumio/Build#225]
This was not noticed in the current version but only in VolumioNext.

Using a USB out to DAC, there is slight noise usually at 5s, 10s and 15s, then it's perfect. This only happens when the tracks started, it never happens after 15s of playback.

**Comment by gkkpch** [comment]
please add platform you are referring to.

**Comment by leafy7382** [comment]
Raspberry Pi 3, thanks.
