### ISSUE TITLE
Add support to boot from SATA, SD card or eMMC on UDOO x86

### ISSUE THREAD

**Issue by codewarriorFX** [volumio/Build#230]
UDOO x86 seems to have problems booting from SD card, SATA controller and 32GB eMMC (Advanced Plus and Ultra models). If someone attempted to boot from a M.2 and have problems, please report it here as well.

Original post:  https://volumio.org/forum/card-boot-udoo-x86-t6986.html

**Comment by codewarriorFX** [comment]
Hi @antnet64 Im using the UDOO x86 with volumio from a USB 3.0 drive for the moment. Looks like the Volumio team is currently working on a solution. I have installed the version 2.201 on the USB then updated to 2.246 on the system updater. I still doesn't show the SD card or eMMC on the fdisk -l list.

I hope they fix this, to install Volumio on the 32GB eMMC :)

**Comment by gkkpch** [comment]
You guys could actually help as I do not have an UDOO X86. Does anyone of you use an linux distribution on it with SD and eMMC. If so, does the boot partition of that distro have a copy of the kernel config. If not, could someone try to copy /proc/config.gz for me?

**Comment by codewarriorFX** [comment]
@gkkpch I ran Ubuntu 17 on the eMMC of the Udoo with no problem. All I need to do is access the eMMC and get the config.gz?

**Comment by gkkpch** [comment]
yes please

**Comment by gkkpch** [comment]
@codewarriorFX  when I mentioned "eMMC won't be in there" I was perhaps too pessimistic, I did select Intel Braswell soc support, comparing the config from your distro and my volumio x86 version may help

**Comment by gkkpch** [comment]
This has been solved with the available dev version for x86.
It has been tested by several community members and confirmed working. 
The version is stable, but as it is a dev version, there is no support for it.
Feedback is welcome nevertheless as it will flow into the Debian stretch verrsion we are working on.
Link to the latest dev: [
https://volumio.org/forum/next-x86-development-kernel-hardware-debian-stretch-t9651.html](url)
