### ISSUE TITLE
Build on clean debian 8.2.0 fails

### ISSUE THREAD

**Issue by Domin6** [volumio/Build#24]
Hi all trying to build an rpi image on a clean Debian install i get this error:

cp: cannot create regular file ‘build/root/usr/bin/qemu-arm-static’: Text file busy
+ su -
/bin/bash: line 1: ./firstconfig.sh: No such file or directory

I installed all required packages listed in the readme.
Any help is appreciated
Also what OS are you using to build this on ?

**Comment by volumio** [comment]
Seems like a typo...  I usually do  ./build.sh -b arm -d pi -v 0.9

I use debian both x32 or x64.  Make sure you have perms on the cloned dir....

**Comment by Domin6** [comment]
This is the command i ran:
sudo ./build.sh -b arm -d pi -v 2.0

I also tried running from root but it gives the same error, here is a bit more before and after:

zlib1g is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Download complete and in download only mode
I: Calculating obsolete packages
Using directory /home/volumio/build/build/root/ for unpacking operations
I: Unpacking complete.
I: Tidying up apt cache and list data.
I: Tidying up apt cache and list data.

Multistrap system installed successfully in /home/volumio/build/build/root/.

cp: cannot create regular file ‘build/root/usr/bin/qemu-arm-static’: Text file busy
+ su -
/bin/bash: line 1: ./firstconfig.sh: No such file or directory
Base System Installed
Unmounting Temp devices
Copying Custom Volumio System Files
Done Copying Custom Volumio System Files

Best regards
Domin6

**Comment by volumio** [comment]
Just betting: try to reboot, maybe you have a qemu instance running...

**Comment by Domin6** [comment]
Did a reboot same error, from what i can gather on google it looks like it might be an issue with bash ?

**Comment by volumio** [comment]
Are you on an actual pi? If no which debian version?  Did you install qemu?

**Comment by Domin6** [comment]
I am on a clean Debian 8.2.0 x64 and i installed all packages stated here on the front page that are required.

However i fixed the problem running it as root, seems the build script do not like sudo so you need to su - root and then run the script from there, then it will work.

**Comment by volumio** [comment]
Ok I ll state it clearly on the Readme then as well

**Comment by gkkpch** [comment]
I think you are also using an very old version of the build scripts, "firstconfig.sh" has been removed a while ago.

**Comment by Domin6** [comment]
gkkpch you are right on the money, looks like my fork was not updated properly.
Sorry for all the troubles

**Comment by gkkpch** [comment]
You may have missed an important update for the PI ARMv6 platform from this afternoon. 
Anything older than that one will not boot the A/A+/B/B+
Enjoy! I'm also build on x64, does throw a warning or an error here and there, but nothing substantial.
Just don't put the build folder on an nfs volume, qemu will crash. 
Have not tried smb, in case of problems it may be for the same reasons :smile: 
Cheers - Gé

**Comment by Domin6** [comment]
Thanks for the hint gkkpch, i saw the update an pulled it in as i am building for rpi1 however the image i get seems faulty.

When i build i get an image file and the build completes but when i dd the image to a card it only seems to have the sqsh file on it.

Under the build i get a lot of these arror on different packages:

I: Extracting libnih1_1.0.3-4.3_armhf.deb...
Warning: unrecognised value 'no' for Multi-Arch field in libnih1_1.0.3-4.3_armhf.deb. (Expecting 'same', 'foreign' or 'allowed'.)

Best regards
Domin6

**Comment by gkkpch** [comment]
Don't worry about the messages below, they're just warnings.
You will have 2 partitions on the image, a vfat boot partition and an ext4 partition with volumio.sqsh on it.
The initramfs will add a 3rd partition, this one is for the volumio data like database, configs, playlists etc.
Initramfs will mount volumio.sqsh as a squash partition and make an overlay with the data partition and switch to as the rootfs.
So, as you seem to have finished the build process succesfully with a .sqsh file, burn the image on an sd and try it.
Gé

On 28.12.2015, at 09:17, Domin <notifications@github.com> wrote:

Thanks for the hint gkkpch, i saw the update an pulled it in as i am building for rpi1 however the image i get seems faulty.

When i build i get an image file and the build completes but when i dd the image to a card it only seems to have the sqsh file on it.

Under the build i get a lot of these arror on different packages:

I: Extracting libnih1_1.0.3-4.3_armhf.deb...
Warning: unrecognised value 'no' for Multi-Arch field in libnih1_1.0.3-4.3_armhf.deb. (Expecting 'same', 'foreign' or 'allowed'.)

Best regards
Domin6

**Comment by Domin6** [comment]
The problem is that i get this Volumio2.0-2015-12-28PI.img file that is 3.5G in size but when i dd it to the sdcard the card only contains 1 partition and if i browse to it, there is only a lost+found and a volumio_current.sqsh file on the card nothing else.

**Comment by gkkpch** [comment]
I don't get it, first you say there is only a 60MB partition (which is boot) and a 1.73Gb (which is the one with volumio.sqsh). That would be as expected for Volumio 2, the 3rd partition (volumio_data) will be created upon boot. The volumio.sqsh is vital, that contains your complete root filesystem, which will be made available while booting. This is a totally different startup as you know from 1.55 and is intentional.
Now you confuse me when you say, there is only one partition.

Perhaps we have another problem here, which size is your card?  Currently only 8 Gb seems to work and that problem is being taken care of. Probably tonight.

Gé


On 28.12.2015, at 18:25, Domin <notifications@github.com> wrote:

The problem is that i get this Volumio2.0-2015-12-28PI.img file that is 3.5G in size but when i dd it to the sdcard the card only contains 1 partition and if i browse to it, there is only a lost+found and a volumio_current.sqsh file on the card nothing else.

**Comment by gkkpch** [comment]
Sorry, made a mistake, the 60Mb partition was mentioned with another issue, not yours. 
Sure the boot partition is not there, how did you "dd"?

**Comment by Domin6** [comment]
I am sure the boot partition is not there, this is my dd commandline:
sudo dd bs=1M if=Volumio2.0-2015-12-28PI.img of=/dev/sdb

My build machine is a virtual machine with no gui, however i transferred the img file to my linux desktop machine, but what program would you like me to open the img file with ?

The mount squash command fails giving the following error:
volumio@volumio-build:~/build$ sudo mount -t squash volumio.sqsh ./sqsh
[sudo] password for volumio:
mount: unknown filesystem type 'squash'

**Comment by gkkpch** [comment]
On my Debian 8.0.1 linux machine it does that with a double-click. That defaults to mounting all partitions of the image, it does that ootb. In case you run Debian, that should work. Could you open a terminal on your linux machine and show all partitions with fdisk -l <image> and show me the output? 
You can also do the same with 'parted' and use the image instead of a device

**Comment by Domin6** [comment]
Ahh i run xubuntu as my primary desktop os, and it seems to lack that feature.
I did however mount it with parted, this lead me to find this strange layout.

(parted) print all
Model:  (file)
Disk /home/volumio/build/Volumio2.0-2015-12-28PI.img: 3720MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:

Number  Start   End     Size    Type     File system  Flags
 1      512B    64.0MB  64.0MB  primary               boot, lba
 2      65.0MB  1920MB  1855MB  primary  ext4

Same results when i look at the sdcard from gparted on my desktop os, primary partition is unknown.

On a side note i had to manually install parted on the build machine before i was able to build any packages, could there perhaps be other packages missing that will make it unable to create the fat32 partition ?

(i documented all my steps so i could perhaps add extra info to the readme, helping others compiling for the first time)

Thanks for taking the time helping with this, its much appreciated :-)

**Comment by volumio** [comment]
The deps are stated in the build.sh (moving to README.md asap) : 
parted squashfs-tools dosfstools multistrap qemu binfmt-support qemu-user-static kpartx 

Let us know!

**Comment by gkkpch** [comment]
I have a patch for the "init"-script, testing it right now on a 32Gb SD

**Comment by Domin6** [comment]
Ahh see now were getting somewhere, i only installed the packages listed in the README so that might be it i can see dosfstools missing aso, in the meantime i also discovered this error so that also gives hint about it missing:

sudo: mkfs.vfat: command not found

Let me install the new packages and i will get back as soon as the build is complete :-)

**Comment by volumio** [comment]
Gé I think that a reliable solution would be to have the data partition created by the script and then enlarged on first boot. The current design may fail if for some reason the first boot gets stopped (for example removing power) at the stage where the partition gets created...
That's what I'm planning to do, hopefully today.

**Comment by volumio** [comment]
Domin, if you find missing packages that are not in the previous list, let me know and I'll add them to the build script.

**Comment by Domin6** [comment]
Yes adding the packages you listed here the img file now works, my rpi1 boots and i am able to login/browse the interface aso.

Thanks for all the help guys and girls :-)
