### ISSUE TITLE
Please clean /var/tmp/ after build

### ISSUE THREAD

**Issue by levindu** [volumio/Build#253]
I mount the volumio_current.sqsh in volumio-2.246-2017-07-31-pi.img.zip to inspect its content. 
`/var/tmp` is not clean and occupied by several mega bytes:

> $ ls var/tmp
mkinitramfs_B4V371  mkinitramfs_IbKY5z
$ sudo du -hs var/tmp
292M    var/tmp

Also, I suggest to clean up unused file, like man and doc files using dpkg filters:
 * https://wiki.debian.org/ReduceDebian
 * https://wiki.ubuntu.com/ReducingDiskFootprint

**Comment by xipmix** [comment]
Many of the ReduceDebian steps have been made already, can you be specific about things that you feel still need to be addressed?
