### ISSUE TITLE
npm install needed

### ISSUE THREAD

**Issue by balbuze** [volumio/Build#28]
With last build script (commit 241e251c8fbc67be5a09401db0d2285f2452f747 ) a npm install is needed so that node starts properly

**Comment by gkkpch** [comment]
Yes, that solves the alsa-controller issue. I will close mine on volumio2

**Comment by balbuze** [comment]
For me it does not solve alsa-controller issue. Only current device is displayed

**Comment by gkkpch** [comment]
what does aplay -l show?

**Comment by volumio** [comment]
Yep guys, is still a work in progress... Sorry for not pointing it out...

**Comment by balbuze** [comment]
I found ! In fact there is no problem...
