### ISSUE TITLE
Banana Pi M2+ on Armbian dont boot.

### ISSUE THREAD

**Issue by educastellini** [volumio/Build#351]
I make a build on my Banana Pi M2+ in the Armbiam and aparently the compiling its ok e made a 2.9Gb image but wen I burn on the emmc or in a card and the image dont boot.
Can help for me...?

Thanks,
Eduardo....

**Comment by gkkpch** [comment]
unfortunately, the one who created the build scripts for armbian does not seem to support it.
There have been multiple failure reports already. 
This also means we have no idea what went wrong, I'm sorry that we can't help.
Armbian build support was supposed to be removed, it has not happened yet, but will be soon.
