### ISSUE TITLE
Unable to boot <nano|orange>pi images

### ISSUE THREAD

**Issue by ashthespy** [volumio/Build#358]
Wanted to update my Volumio after a `volumio pull` didn't really work.

Build a new image from master - but am unable to boot them.
Tried both with the orangepilite and the nanopineo2

The image loads the u-boot and kernel, but errors at 
```
## Executing script at 44000000
Wrong Ramdisk Image Format
Ramdisk image is corrupt or invalid
SCRIPT Failed: continuing...
```
Any ideas? (Image creation log at https://pastebin.com/2QuXnggG)

**Comment by gkkpch** [comment]
I did not seen any issue in your log, did you check your config file, is it OK (compared to a working one)?
As OrangePI builds are not an officially supported, you would be better off to post your issues in the Community Portings section where Paul (pkendall64) might be able to help you. 
He wrote the scripts and maintains the OrangePI builds.

**Comment by ashthespy** [comment]
@gkkpch Sorry for the false alarm. I was building the arch separately (`-b armv7`), and then using that to build images for both the nanopineo2 and the orangepilite. 
Building the arch together with the device seemed to have worked.
I was also not entirely sure myself, as I spun up a separate fresh Ubuntu 16.04 installation to build these - my normal 18.04 was having issues with multistrap as already noted here. :-)

**Comment by ashthespy** [comment]
Sorry - not been the brightest today - I had switched branches to test my toolchain setup. What I just build and booted was an old branch (https://github.com/volumio/Build/compare/master...ashthespy:opi) 
Either way, it builds and boots fine. Now to figure out why the current master doesn't!
