### ISSUE TITLE
Building - Issue with `binfmt_misc` setting?

### ISSUE THREAD

**Issue by ashthespy** [volumio/Build#371]
Quick question - am I being daft, or are we registering the `arm` binary format only during x86 image builds?
https://github.com/volumio/Build/blob/d4ba5d865676599bf64c88c037f111f550e1b67a/build.sh#L175-L183

added in 1f1a510abe75076989fe2743dc27b3612bc44c6c

**Comment by gkkpch** [comment]
I must admit that I never paid much attention to the main build script, it was a given.
It might look odd, but I can't really grasp what this was needed for, neither arm or x86.
@Michelangelo?

**Comment by ashthespy** [comment]
This is the magic string to to run arm binaries using `qemu`. 
I tracked down my `chroot: failed to run command '/bin/bash': Exec format error` error down to this - on my host, `binfmt_misc` wasn't getting activated.

**Comment by gkkpch** [comment]
Well this can't be toatally wrong, because we would not have been able to build any arm device on an x64 platform.

**Comment by ashthespy** [comment]
Hmm - unsure about that - it needs to be registered only once on the first build right?

**Comment by gkkpch** [comment]
are you sure your have binfmt_misc support installed?

**Comment by gkkpch** [comment]
I might be easier for you to make a known, clean debian jessie install, add the prerequisites and then build?

**Comment by ashthespy** [comment]
>are you sure your have binfmt_misc support installed?

>I might be easier for you to make a known, clean debian jessie install, add the prerequisites and then build?

I am on a fresh Jessie VM here. It's a journey down the rabbit hole - my old Ubuntu VM builds images just fine.
```shell
$ apt list git squashfs-tools kpartx multistrap qemu-user-static samba debootstrap parted dosfstools qemu binfmt-support qemu-utils
Listing... Done
binfmt-support/oldstable,now 2.1.5-1 amd64 [installed]
debootstrap/oldstable,now 1.0.67+deb8u1 all [installed]
dosfstools/oldstable,now 3.0.27-1 amd64 [installed]
git/oldstable,now 1:2.1.4-2.1+deb8u7 amd64 [installed]
kpartx/oldstable,now 0.5.0-6+deb8u2 amd64 [installed]
multistrap/oldstable,now 2.2.0 all [installed]
parted/oldstable,now 3.2-7 amd64 [installed]
qemu/oldstable,now 1:2.1+dfsg-12+deb8u10 amd64 [installed]
qemu-user-static/oldstable,now 1:2.1+dfsg-12+deb8u10 amd64 [installed]
qemu-utils/oldstable,now 1:2.1+dfsg-12+deb8u10 amd64 [installed]
samba/oldstable,now 2:4.2.14+dfsg-0+deb8u11 amd64 [installed]
squashfs-tools/oldstable,now 1:4.2+20130409-2 amd64 [installed]
```

**Comment by gkkpch** [comment]
then I don't know. 
Two weeks ago I helped someone building a customized version of Odroid N2 (not released yet), she had no issues with jessie.
What image are you trying to build?

**Comment by ashthespy** [comment]
For traceability, managed to fix my other issues thanks to @gkkpch help, and a jessie host on an older kernel. 

But I am still unsure what this `:arm:M::` magic string is doing under the `x86` section! 
Any ideas @volumio?

**Comment by ashthespy** [comment]
>But I am still unsure what this :arm:M:: magic string is doing under the x86 section!

I was doing some image building and came across this magic string again -  @gkkpch , @volumio  When your playing around with an `x86` build next time, could you check if the is really required? 
Looking at [`volumioconfig.sh`](https://github.com/volumio/Build/blob/master/scripts/volumioconfig.sh) we don't seem to be running any arm specific commands?

**Comment by gkkpch** [comment]
to begin with, i think the current code is wrong, moreover, i believe we do not need it at all. I’ve tried it and it appears to work just as well without it, i guess it is already set when installing qemu.

**Comment by ashthespy** [comment]
This was an old relic and indeed not needed :-)
