### ISSUE TITLE
Any update for Volumio2 on TV BOX S9xxx S8xxx

### ISSUE THREAD

**Issue by godt2p4** [volumio/Build#374]
I haven't found any update on TV Box S9xxx S8xxx since this January, that is quite a pity.
I'm wondering if this version has been closed with no update any more.
Thank you.

**Comment by gkkpch** [comment]
The Volumio version for Amlogic TV boxes is not maintained by us, 
That version was created by user balbes150, I'm not sure whether he dropped it.

We would need to create a version which we can maintain ourselves.
In that case, MyVolumio could be made available too.
Let's see if anything changes the next few months.

**Comment by godt2p4** [comment]
Thanks, dude!

**Comment by NellyWhadsDev** [comment]
Hey @gkkpch Any updates on this? Will @150balbes continue to maintain S9xxx variants (including the A311D based Khadas VIM3)?

**Comment by gkkpch** [comment]
sorry for the delay, I'be been on a long leave. 
No news here, I'm not sure if @150balbes is planning anything.
I've done an Odroid N2 release, with an S922X. VIM3 might be very similar, but certainly not the same and not sure where @150balbes would pull his kernel from...

**Comment by gkkpch** [comment]
I could add myvolumio functionality to the S9xxx variants build script, but they will only work if we generate the image. Any demands??

**Comment by S199pWa1k9r** [comment]
Hi [https://github.com/gkkpch] you can add support Khadas VIM3?

**Comment by gkkpch** [comment]
Nothing has been planned for the VIM3 because for these there is hardly any demand. Technically it would be very similar to the Odroid N2 version we did. But perhaps in the future when demand is there. We can't do it just for a handful of users.

For VIM3L we are investigating, because it looks as this one is more suitable for media type of applications plus there are already requests for it.

**Comment by ectornalta2** [comment]
sou brasileiro muitos aqui não tinha conhecimentos desse projeto mais eu mesmo ja sou usuário da versão na caixa box mesmo sem muitas melhorias e muito boa conseguir melhoras algumas coisas nela mais seria muito bom se esse projeto tivesse um avanço ia da muito certo
