### ISSUE TITLE
Raspberry PI 4

### ISSUE THREAD

**Issue by volumio** [volumio/Build#378]
- Not been able to start Volumio with kernel 5.19.56 ( see https://github.com/volumio/Build/tree/pi/4.19.56)
- Even with this kernel, all the *4 files are not properly copied
- With this kernel, hostapd refuses to start

@macmpi can you help on that?

**Comment by macmpi** [comment]
Hi,
Happy to try to help, but I'm quite blind as I've not bought a Pi4 yet...

So, you do not have the same list of firmware files as of [raspbian lite image](https://downloads.raspberrypi.org/raspbian_lite_latest)?
Mind **_kernel7l.img_** is specific to Pi4

On hostapd, I remember reading some issue on raspberrypi.org forum (maybe 4.19 thread) that it needed latest buster-friendly version or something...(will try to find reference).

**Comment by volumio** [comment]
Hi, we do have the latest imgs, what we miss are files like: start4.elf etc

Can you drop me an email to info@volumio.org?

**Comment by macmpi** [comment]
You may want to double-check your build machine the latest rpi-update ([was updated for Pi4 support](https://github.com/Hexxeh/rpi-update/commits/master/rpi-update))

**Comment by volumio** [comment]
Made some progress today, but noticed that the WANT_PI4 flag triggers a call to df which does not work in our build system. 
Re wpa supplicant, seems the only way is to compile it as we do fail too many dependencies

**Comment by macmpi** [comment]
Yes, noticed the `check_partition` thing that was added recently: maybe they could do it in a less intrusive way in case it is applied on a directory not a partition... Some other distribution build may have same issue. Worth suggesting to hexxeh repo maybe.
Alternatively we could avoid rpi-update altogether by just cloning the repo with git (and remove unnecessary files)?

Too bad for `hostapd` :(  Hopefully that will be the only one needing such attention, awaiting for Buster migration.

**Comment by volumio** [comment]
Yes I think it would be good to notify hexxeh and maybe do a PR ;)

Will keep you posted on the progress tomorrow ;)

**Comment by volumio** [comment]
@macmpi 
Managed to get a bootable image:
http://updates.volumio.org/pi/volumio/0.136/volumio-0.136-2019-07-06-pi.img.zip

What we miss:
- Wireless seems not to be working on PI4, maybe we miss the firmware?
- Hostapd...

**Comment by macmpi** [comment]
> What we miss:
>     Wireless seems not to be working on PI4, maybe we miss the firmware?

Check this ;)
Need to [add "manually" ](https://github.com/volumio/Build/blob/pi/4.19.56/scripts/raspberryconfig.sh#L144-L147)until we get to Buster.
```
Package: firmware-brcm80211
Source: firmware-nonfree
Version: 1:20190114-1+rpt2
Architecture: all
Maintainer: Debian Kernel Team <debian-kernel@lists.debian.org>
Installed-Size: 15386
Suggests: initramfs-tools
Multi-Arch: foreign
Homepage: https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git
Priority: optional
Section: non-free/kernel
Filename: pool/main/f/firmware-nonfree/firmware-brcm80211_20190114-1+rpt2_all.deb
Size: 4335400
SHA256: 804bc9129ed65cbe27e14c1b92b67f65f6dde37294b11a901279eb8ce5ffdfc1
SHA1: 2269ccd21e10ec3bd89e0fe2ba9d20105229afbc
MD5sum: 41d461d60303d1736a5b53c6fd1a0f4a
Description: Binary firmware for Broadcom/Cypress 802.11 wireless cards
 This package contains the binary firmware for wireless network cards
 supported by the brcmsmac or brcmfmac driver.
 .
 Contents:
  * Broadcom 802.11 firmware, version 610.812 (brcm/bcm43xx-0.fw)
  * Broadcom 802.11 firmware header, version 610.812
    (brcm/bcm43xx_hdr-0.fw)
  * Broadcom BCM43143 USB firmware (brcm/brcmfmac43143.bin)
  * Broadcom BCM43143 SDIO firmware (brcm/brcmfmac43143-sdio.bin)
  * Broadcom BCM43236 firmware (brcm/brcmfmac43236b.bin)
  * Broadcom BCM43241 rev 0-3 firmware (brcm/brcmfmac43241b0-sdio.bin)
  * Broadcom BCM43241 rev 4 firmware (brcm/brcmfmac43241b4-sdio.bin)
  * Broadcom BCM43241 rev 5+ firmware (brcm/brcmfmac43241b5-sdio.bin)
  * Broadcom BCM43242 firmware (brcm/brcmfmac43242a.bin)
  * Broadcom BCM4329 firmware (brcm/brcmfmac4329-sdio.bin)
  * Broadcom BCM4330 firmware (brcm/brcmfmac4330-sdio.bin)
  * Broadcom BCM4334 firmware (brcm/brcmfmac4334-sdio.bin)
  * Broadcom BCM43340 firmware (brcm/brcmfmac43340-sdio.bin)
  * Broadcom BCM4335 firmware (brcm/brcmfmac4335-sdio.bin)
  * Broadcom BCM43362 firmware (brcm/brcmfmac43362-sdio.bin)
  * Broadcom BCM4339 firmware (brcm/brcmfmac4339-sdio.bin)
  * Broadcom BCM43455 firmware, version 7.45.154
    (brcm/brcmfmac43455-sdio.bin)
  * brcm/brcmfmac43455-sdio.clm_blob
  * NVRAM file for BCM43455 (brcm/brcmfmac43455-sdio.txt)
  * Broadcom BCM43430 rev 0 firmware (brcm/brcmfmac43430a0-sdio.bin)
  * Broadcom BCM43430 rev 1+ firmware, version 7.45.98.38
    (brcm/brcmfmac43430-sdio.bin)
  * NVRAM file for BCM943430 (brcm/brcmfmac43430-sdio.txt)
  * Broadcom BCM4350 rev 0-4 firmware (brcm/brcmfmac4350-pcie.bin)
  * Broadcom BCM4350 rev 5+ firmware (brcm/brcmfmac4350c2-pcie.bin)
  * Broadcom BCM4354 firmware, version 7.35.79.57
    (brcm/brcmfmac4354-sdio.bin)
  * Broadcom BCM4356-PCIe firmware (brcm/brcmfmac4356-pcie.bin)
  * Broadcom BCM4356-SDIO firmware] (brcm/brcmfmac4356-sdio.bin)
  * Broadcom BCM43569 firmware (brcm/brcmfmac43569.bin)
  * Broadcom BCM43570 firmware (brcm/brcmfmac43570-pcie.bin)
  * Broadcom BCM4358 firmware (brcm/brcmfmac4358-pcie.bin)
  * Broadcom BCM43602 AP-mode firmware (brcm/brcmfmac43602-pcie.ap.bin)
  * Broadcom BCM43602 firmware (brcm/brcmfmac43602-pcie.bin)
  * Broadcom BCM4366 firmware (brcm/brcmfmac4366b-pcie.bin)
  * Broadcom BCM4371 firmware (brcm/brcmfmac4371-pcie.bin)
  * Cypress CYW4373-USB firmware (brcm/brcmfmac4373.bin)
  * Cypress CYW4373-SDIO firmware (brcm/brcmfmac4373-sdio.bin)

```

**Comment by volumio** [comment]
It works, thanks!
Now just hostapd is left ;)

**Comment by volumio** [comment]
Made it;)

Now we have a full blown PI4 image

**Comment by macmpi** [comment]
Congrats, that was quick!
Next time they will make it harder :p

**Comment by macmpi** [comment]
@volumio BTW, would you have one of those Edimax EW-7811Un adapter?
Any chance you can try AP mode works with it, and Pi won't crash upon client connection under 4.19 kernel? (make sure `rtl8192cu` blacklist is set)

**Comment by hukl** [comment]
> Made it;)
> 
> Now we have a full blown PI4 image

Where can I download this image? The one on the website still seems the old one

(Disclaimer: I'm new to this volumio universe)

**Comment by piffio** [comment]
https://forum.volumio.org/experimental-volumio-build-for-raspberry-t12640.html

**Comment by macmpi** [comment]
@volumio see https://github.com/Hexxeh/rpi-firmware/commit/ce2a9f85a6fd88f8c42ef54b7bad99b42e76e403 with Hifiberry DACplusADC PRO support (and lots of fixes since .56)

**Comment by volumio** [comment]
Thanks! I'll give it a try
