### ISSUE TITLE
wireless.service delays boot for about 30s

### ISSUE THREAD

**Issue by 0unknwn** [volumio/Build#381]
I use a Raspberry Pi Zero. It needs about one minute to start. When running `systemd-analyze critical-chain` I can see that the `wireless.service` delays the startup process for more then 30 seconds, which is a lot and makes volumio nearly unusable for me. 
A default Raspbian only needs about 18 seconds to start.

Also I find 268 lines of JavaScript a bit overkill for just having an automatic hotspot. 
I wrote something to achieve the same much easier thanks to `systemd`.

[Maybe you could have a look at it.](https://github.com/0unknwn/autoAccessPoint/blob/master/auto-hotspot)

**Comment by volumio** [comment]
Hi, really like your script for hotspot.
The reason for wireless to delay 30 seconds is quite simple: we need to make sure that network is initialized before starting Volumio (since many services depend on it). 
As for being an overkill, we need to handle lot of scenarios...
