### ISSUE TITLE
xbindkeysrc.service does not start

### ISSUE THREAD

**Issue by gvolt** [volumio/Build#386]
The xbindkeysrc.service does not start.

`systemctl status -l xbindkeysrc` shows

```
xbindkeysrc.service - Xbindrc
   Loaded: loaded (/lib/systemd/system/xbindkeysrc.service; enabled)
   Active: failed (Result: start-limit) since Mon 2019-08-05 10:17:13 UTC; 2s ago
  Process: 26462 ExecStart=/usr/bin/xbindkeys -X :0 -f /etc/xbindkeysrc (code=exited, status=0/SUCCESS)
 Main PID: 26462 (code=exited, status=0/SUCCESS)

Aug 05 10:17:13 volumio systemd[1]: xbindkeysrc.service holdoff time over, scheduling restart.
Aug 05 10:17:13 volumio systemd[1]: Stopping Xbindrc...
Aug 05 10:17:13 volumio systemd[1]: Starting Xbindrc...
Aug 05 10:17:13 volumio systemd[1]: xbindkeysrc.service start request repeated too quickly, refusing to start.
Aug 05 10:17:13 volumio systemd[1]: Failed to start Xbindrc.
Aug 05 10:17:13 volumio systemd[1]: Unit xbindkeysrc.service entered failed state.
```

Changing the line `Restart=always` to `Restart=on-failure` in the service unit solves the issue.

System: Volumio 2.599 on Raspberry Pi 3B

P.S. Issue reported also [here](https://github.com/volumio/Volumio2/issues/1789).

**Comment by ashthespy** [comment]
Is this still a issue with the switch to `triggerhappy` in 859858f6eee0b4de0db7aa9e3dc878e08afe0fa3?
I do see that the `xbindkeysrc .service` file is still checked in, but a quick glance shows it's not being copied into the rootfs? https://github.com/volumio/Build/blob/13c723d98523acfdb1d282b7aa95a6b74d33cad8/scripts/volumioconfig.sh#L461-L484

**Comment by gvolt** [comment]
While the file is still present in `/lib/systemd/system/` the triggerhappy binary [seems to be missing](https://github.com/volumio/Build/commit/859858f6eee0b4de0db7aa9e3dc878e08afe0fa3#commitcomment-42622769) from the system (Raspberry Pi). OTOH I found the triggerhappy daemon `thd` is present in `/usr/sbin` and the triggerhappy.service is running (Volumio 2.853):

`systemctl status -l triggerhappy
● triggerhappy.service - LSB: triggerhappy hotkey daemon
   Loaded: loaded (/etc/init.d/triggerhappy)
   Active: active (running) since Sun 2020-12-06 17:56:50 CET; 6 days ago
   CGroup: /system.slice/triggerhappy.service
           └─762 /usr/sbin/thd --daemon --triggers /etc/triggerhappy/triggers.d/ --socket /var/run/thd.socket --pidfile /var/run/thd.pid --user nobody /dev/input/event0 /dev/input/event1

Dec 06 17:56:49 volumio systemd[1]: Starting LSB: triggerhappy hotkey daemon...
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio triggerhappy[705]: Unable to parse trigger line:
Dec 06 17:56:50 volumio systemd[1]: Started LSB: triggerhappy hotkey daemon.
`
So the issue is probably solved and the xbindkeysrc.service not started just cosmetic.

**Comment by ashthespy** [comment]
>  the triggerhappy binary [seems to be missing](https://github.com/volumio/Build/commit/859858f6eee0b4de0db7aa9e3dc878e08afe0fa3#commitcomment-42622769) from the system (Raspberry Pi).

Ah, don't fall for that ;-) its added in the `multistrap` stage in [`recipes/arm.conf`](https://github.com/volumio/Build/blob/168ba7444df98cd868db72f24faec0b6346489cc/recipes/arm.conf#L57-L61)

> the file is still present in `/lib/systemd/system/`

Still not sure how that happens - this is in on Volumio 2.853?

**Comment by gvolt** [comment]
> Ah, don't fall for that ;-) its added in the `multistrap` stage in [`recipes/arm.conf`](https://github.com/volumio/Build/blob/168ba7444df98cd868db72f24faec0b6346489cc/recipes/arm.conf#L57-L61)

I saw that, and did a quick search for a package named "triggerhappy" with `apt list --installed | grep triggerhappy`, `dpkg --list | grep triggerhappy` and `whereis triggerhappy` which all showed nothing. But "triggerhappy" was probably the wrong term to look for...

> Still not sure how that happens - this is in on Volumio 2.853?

Yes.

> EDIT: Just to clarify - you mean here in the repo right? and not on the device?

`xbindkeysrc.service` is still present in `/lib/systemd/system/` on the device.

**Comment by ashthespy** [comment]
> But "triggerhappy" was probably the wrong term to look for...

Yep, it should be
```
/usr/sbin/th-cmd
/usr/sbin/thd
```




> `xbindkeysrc.service` is still present in `/lib/systemd/system/` on the device.

Found it! 
https://github.com/volumio/Build/blob/13c723d98523acfdb1d282b7aa95a6b74d33cad8/scripts/configure.sh#L60-L61

Lets leave this open as a reminder to remove it 👍

**Comment by xipmix** [comment]
Is this the outstanding item in #401? 

Is it correct that all that is needed here is to remove the ```xbindkeysrc.service``` unit file, because the 'triggerhappy' package implements the same functionality?

**Comment by ashthespy** [comment]
Fixed in `volumioOS` branch https://github.com/volumio/Build/pull/470
