### ISSUE TITLE
Running Volumio on Docker

### ISSUE THREAD

**Issue by marius-hi** [volumio/Build#387]
Hi guys, as now Raspberry 4 offers more possibilities it would be really nice if we can run Volumio through a Docker container. Is there any plan to support this in the future?

I can see that the command supports a parameter to create a docker layer, however this doesn't work for me. The img file is created but at the end I get the following error:
```
Creating docker layer
open VolumioRootFS2.0.tar.gz: no such file or directory
```

**Comment by thiagobucca** [comment]
did you ever run past this? i'm having the same issue.

**Comment by dmytro-shchurov** [comment]
I have something here.
First, volumio build repo does not contain commands to create a `VolumioRootFS$VERSION.tar.gz` file which is supposed to be used during importing into docker.
Secondly, Volumio uses squashfs (despite of 64GB sd cards for a penny). 
so, if you passed a step where img file is created, you have to have `Volumio.sqsh` file next to the image in your build directory.

There is no difference whether you mount the img file and use it's partition 2, or mount `Volumio.sqsh` file directly, a result must be the same
```
sudo mkdir /mnt/rootfs
sudo mount Volumio.sqsh /mnt/rootfs -t squashfs -o loop
```
Then make a zipped tar with
```
sudo tar -zvcf VolumioRootFS.tar.gz /mnt/rootfs
```
And import it then
```
docker import VolumioRootFS.tar.gz volumio:latest

$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
volumio                    latest              8c847025dc68        3 seconds ago       42.8MB
ghcr.io/linuxserver/plex   latest              007c715bc94f        5 days ago          328MB
```

In my case it says unsquashed root has a size of 41M (so as docker image), but `loop0p2` partition (you can use `losetup -P /dev/loop0 <img_file>.img` command to mount the img file) has 2GB size (however it contains only one squashed 20M file, so, either this is my build process error, or this is expected), thus I'm not sure will it work or not. Sorry.

I'll be continue testing and let you know soon.
