### ISSUE TITLE
Migration to Debian Buster 

### ISSUE THREAD

**Issue by ashthespy** [volumio/Build#401]
Picking up from #388 and the [x86-debian-buster forum thread](https://forum.volumio.org/volumio-x86-debian-buster-debugging-party-beta-t13957.html), would like to use this to track issues/bugs encountered during the migration to Buster.

####  Beta builds
- Check [x86-buster thread](https://forum.volumio.org/volumio-x86-debian-buster-debugging-party-beta-t13957.html)
- [Check out the forum thread](https://forum.volumio.org/volumio-debian-buster-beta-raspi-images-debugging-t14059.html) for more up to date images.. 

#### Know issues 
- [x] Missing Volumio specific binaries (`volumio_init_updater`)
   - Using `volumio_init_updater-v2` instead 
- [x] Buster's version of `shairport-sync` wont start with current service
- [x] `hostapad` config issues prevent it from starting up 
- [x] `xbindkeysrc` issues 
- [x] `dhcpd` issues

#### Requires investigation 
- [x] A replacement for `udisk-glue` - suggestions include [`udiskie`](https://github.com/coldfix/udiskie/wiki) and [`udevil`](https://ignorantguru.github.io/udevil/)
- [x] `ifconfig` syntax change issues - https://github.com/volumio/Volumio2/issues/1502 
 - Solved temporarily by reverting Predictable Network Interface naming  

#### House keeping
- [x] Clean-up `sshd_config`
- [x] Update nodejs ([8.xx is EOL as of 31-12-2019](https://github.com/nodejs/Release#end-of-life-releases)). 
  -  *With a few tweaks, Node 12.xx seems to work fine..*
- [x] Update legacy `node` paths over at [`volumio/Volumio2`](https://github.com/volumio/Volumio2) - https://github.com/volumio/Volumio2/pull/1902

**Comment by gkkpch** [comment]
@volumio already created a node alternative for udisk-glue.
Just change NODE_MOUNT_HANDLER in /volumio/.env from false to true

**Comment by volumio** [comment]
Thanks @ashthespy very useful! 
I will take care of volumio specific binaries, if you are available I can tell you how to compile them as well.
Can you let me know what are the tweaks necessary for node 12.xx ?

**Comment by ashthespy** [comment]
> Just change NODE_MOUNT_HANDLER in /volumio/.env from false to true 

Interesting, will enable it!

>I will take care of volumio specific binaries, if you are available I can tell you how to compile them as well.

Sure, I have native arm/armhf/arm64 if we can't cross compile..

> Can you let me know what are the tweaks necessary for node 12.xx ?

Mainly was with the native modules, will dig up the scripts from my device later this evening..

**Comment by volumio** [comment]
Thanks!

**Comment by ashthespy** [comment]
@gkkpch @volumio  Other than the Volumio binaries, tentatively got the rest up and running (on Node 12 as well) - will post on the forums to get volunteers to weed out more issues..

**Comment by MikeX-s** [comment]
Hello,
How is migration going? 
BR

**Comment by ashthespy** [comment]
This issue is a bit stale, [check out the forum thread](https://forum.volumio.org/volumio-debian-buster-beta-raspi-images-debugging-t14059.html) for more up to date images..

**Comment by taliesin** [comment]
Maybe known, but the nodejs package is not put on hold in the current 3.010 image (Aug 21), so before updating any packages:

`echo nodejs hold | sudo dpkg --set-selections`
`dpkg --get-selections | grep hold`
nodejs hold

After that you may update without troubles, otherwise you will end up with version 10.something, killing volumio.

**Comment by ashthespy** [comment]
Ah yes, I reverted back to NodeJS `v8` from `v14` to ensure plugin compatibility, but given that node `v14` is the current LTS we should bite the bullet and move Volumio to it.. 

PS: Thanks for bumping this thread up - current Volumio is really showing it's age..  Node v8 is EOL as of Dec 31st 2019, and Jessie as of June 30, 2020..

**Comment by taliesin** [comment]
Is the update feature working on the Beta? Maybe you could provide a version with V14, so plugin developers can test against it?
Personally I don't use any plug-ins, but using current versions as much as possible would definitely help progressing to a robust base version.

Probably also increasing pressure on plug-ins.
Besides, are you the only one to drive this process?

**Comment by tlmyasirs** [comment]
I installed the Shairport Sync manually. It works but only making the audio out via HDMI, cant get to 3.5mm jack.
![rpi](https://user-images.githubusercontent.com/11702270/102682717-1de81f80-41e5-11eb-9c56-3acb2bf13457.JPG)

**Comment by xipmix** [comment]
Can someone explain what the problem is here? I don't see it in the thread apart from the systemd service not starting.
   ```xbindkeysrc``` issues

**Comment by ashthespy** [comment]
> Can someone explain what the problem is here? I don't see it in the thread apart from the systemd service not starting.
>    ```xbindkeysrc``` issues
> 

Sorry, missed my notifications.. 
From my side, I've been running buster based Volumio since early 2019.. It's been working quite well (for my simple use cases) on my little fruity orange|nano pi's.

For Raspberry specific quirks, this issue now is quite stale, and the forum thread's got more up to date info..

The `xbindkeysrx` is just a relic that needs cleaning up..
There are many more such things over at https://github.com/volumio/Build/issues/429

**Comment by volumio** [comment]
xbindrc shall just be cleaned up as it has been superseded by triggerhappy. See:
https://github.com/volumio/Build/commit/859858f6eee0b4de0db7aa9e3dc878e08afe0fa3

Other stuff:
- Make sure the system does not perform unattended upgrades. See apt-daily upgrade timer 
- Restore naming of pi (when everything is confirmed to work)

**Comment by ashthespy** [comment]
> Make sure the system does not perform unattended upgrades. See apt-daily upgrade timer

That should be a non issue -- upgrades are installed only if `unattended-upgrades` is installed. The `apt-daily` seems to be used to keep the cache updated (as I understood it).
```
volumio@volumio:~$ systemctl list-timers
NEXT                         LEFT     LAST                         PASSED       UNIT                         ACTIVATES
Tue 2021-01-12 06:59:29 UTC  12h left Mon 2021-01-11 06:43:09 UTC  11h ago      apt-daily-upgrade.timer      apt-daily-upgrade.service
Tue 2021-01-12 14:23:50 UTC  19h left Mon 2021-01-11 18:31:09 UTC  3min 11s ago apt-daily.timer              apt-daily.service
Tue 2021-01-12 16:29:09 UTC  21h left Mon 2021-01-11 16:29:09 UTC  2h 5min ago  systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service

3 timers listed.
Pass --all to see loaded but inactive timers, too.
# We don't have unattended-upgrades
volumio@volumio:~$ apt-cache policy unattended-upgrades
unattended-upgrades:
  Installed: (none)
  Candidate: 1.11.2
  Version table:
     1.11.2 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```

**Comment by rawdlite** [comment]
> Picking up from #388 and the [x86-debian-buster forum thread](https://forum.volumio.org/volumio-x86-debian-buster-debugging-party-beta-t13957.html), would like to use this to track issues/bugs encountered during the migration to Buster.
> * [Raspberry Pi Volumio-3.003-2020-02-25-pi

Installed latest image on a Raspberry Pi 4B with Digi One and Touchscreen.
This are the issues I encountered so far:
- external Drive on USB3 is not auto mounted.
I could than do `sudo mount /dev/sda1 /mnt/USB` and my files were scanned without errors. (This was my main Problem on Volumio 2 and seems to be solved with the newer version of mpd now)
After a reboot no device was mounted and my library was gone.

- switching to a different wlan did no succeed. I see the right entries in wpa_supplicant.conf yet ifconfig does not report the changes being done.
The new connection is also not shown in the settings screen.

- on playing a file I get an alsa error hw2:0 not found. `aplay -l` reports the Digi One to be configured.

Let me know if you want further details or tests.

**Comment by ashthespy** [comment]
> Installed latest image on a Raspberry Pi 4B with Digi One and Touchscreen.

Not sure which is this latest image tested, but as mentioned in https://github.com/volumio/Build/issues/401#issuecomment-629154056 this issue is quite stale, and the latest images are over in the forums..

**Comment by rawdlite** [comment]
Quick update:
The alsa error seems to be a known issue with touchscreens. I worked around by creating a dummy device.
May i state that relying on a device index might not be the most reliable approach. I would like to suggest creating an alsa alias device 'volumio', have mpd, shairport etc. point to that and on changes just change the definition of the alsa alias device (single place).

The wlan issue miraculously disappeared. Probably an issue with Vodafone. So please ignore that.

so only the automount issue remains. 
As udisksctl mount -b /dev/sda1 works it seems to be an issue with dbus notification.

**Comment by rawdlite** [comment]
Oh sorry just saw your comment. 
My release tsted was Raspberry Pi Volumio-3.003-2020-02-25-pi 
Will head over to the forum then.

**Comment by tlmyasirs** [comment]
Raspberry Pi Volumio-3.015-2021-01-03-pi 190
installed the Shairport `Sync 3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc ` manually. Because it didn't work by default. still airplay is not working at all

**Comment by ashthespy** [comment]
> 
> 
> Raspberry Pi Volumio-3.015-2021-01-03-pi 190
> installed the Shairport `Sync 3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc ` manually. Because it didn't work by default. still airplay is not working at all

Did you look through the forum thread, particularly [these few posts](https://community.volumio.org/t/volumio-debian-buster-beta-raspi-images-debugging/11988/380?u=ashthespy) on how to fix Airplay on the `3.015` image?

**Comment by tlmyasirs** [comment]
> > Raspberry Pi Volumio-3.015-2021-01-03-pi 190
> > installed the Shairport `Sync 3.3.8rc3-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc ` manually. Because it didn't work by default. still airplay is not working at all
> 
> Did you look through the forum thread, particularly [these few posts](https://community.volumio.org/t/volumio-debian-buster-beta-raspi-images-debugging/11988/380?u=ashthespy) on how to fix Airplay on the `3.015` image?

I followed the instructions given there and it fixed the issue

**Comment by volumio** [comment]
@ashthespy I suggest to avoid manual intervention to builds, as it will complicate our debugging and testing in this phase ;)

**Comment by ashthespy** [comment]
@volumio  Yep, hopefully the official Buster images come out soon, I've run out of space on my Drive to push new images - hence the manual intervention instead of a new build :-)

**Comment by volumio** [comment]
@ashthespy yep I agree! We shall be able to release the first beta this WE ;)
