### ISSUE TITLE
Updating to node v14 LTS

### ISSUE THREAD

**Issue by ashthespy** [volumio/Build#402]
Splitting out from #401 as this requires more work than initially though. 
>#### House keeping
- Clean-up `sshd_config`
- Update nodejs ([8.xx is EOL as of 31-12-2019](https://github.com/nodejs/Release#end-of-life-releases)). 
  -  *With a few tweaks, Node 12.xx seems to work fine..*

I just realised that node 12.xx [dropped official binaries for ARMv6](https://github.com/nodejs/nodejs.org/pull/2205), relegating them to [unofficial-builds.nodejs.org](https://unofficial-builds.nodejs.org/download/release/v12.16.1/) instead. 

Now I haven't looked into performance stats for `armv7` vs `arm6l` node, but does it make sense for all pi platforms to run on this "experimental" `arm6l` binary? 

I could build two images for testing/benchmarking "real world" usage if someone is up for it.

**Comment by volumio** [comment]
@ashthespy PI should run arm6l otherwise we will not support older PI models, so yes it does make sense...

**Comment by ashthespy** [comment]
I closed https://github.com/volumio/Volumio2/pull/1902 and released should update this as well..

Node v14 becomes the active LTS version [in a few weeks](https://github.com/nodejs/Release#release-schedule), so we should probably skip node v12. 
Node v14 should work *mostly* out of the box now that https://github.com/c4milo/node-inotify/pull/76 is merged.  I already tested a few Buster images with it and it seemed to work.

So we only have the issue of no official support for `arm6l` from newer node versions.

**Comment by ashthespy** [comment]
Switched in https://github.com/volumio/Build/commit/319a3312f455da3638a89e6489ca7748dfdbc709
