### ISSUE TITLE
Impossible to start any music after few days

### ISSUE THREAD

**Issue by kmiterror** [volumio/Build#405]
After few weeks of using volumio it hanged for good (couldn't play any music), and after a reset it didn't wanted to boot up.
At first I suspected that the SD card is broken, but after some investigation I discovered that the /var/log partition is full. 

It looks like - in my use case - spotify plugin produces around 1MB of logs every day. 
After removing log file everything went back to normal. 
Since the /var/log is a 20MB partition, it was certain that the issue will comeback soon.
Making this partition bigger will only defer the problem. 

What I did was installing logrotate + running daily cron job.
This ensures that volumio.log is partitioned every day and only last 7 logs are kept.
I think that it might be worth to implement it in the base image of volumio. 
This will ensure that volumio won't get broken because of extensive logging.

I propose to add logrotate to run every hour (cron.hourly)
1. It will partition logs "daily" OR if size exceeds 500KB 
2. Maximum number of 7 logs will be kept.

This means, that in worst case scenario you will have 7x 500KB = 3.5MB of logs.
The hidden consequence: in scenario when something writes a lot to logs, all 7 log files might be filled up in single day (or even few hours). 
But still, probably this is better than making the whole system unusable (not only volumio writes to /var/log)
 
I might implement it but I need some guidance on how to modify volumio base image
Any edge cases that I missed? 
I'm open for discussion.

**Comment by kmiterror** [comment]
PS I just read a bit, and it's probably best not to use **cron** but **systemd timers** because they are already baked into system.

I also found that there is volumiologrotate.service already, but is it running on a schedule or only after boot up?

**Comment by volumio** [comment]
THe volumiologrotate does exactly that: once the total log size reaches about 18M it cleares them

**Comment by kmiterror** [comment]
Right, but does it run every hour or daily or only when after boot?

**Comment by volumio** [comment]
It checks every minute if logs are more than 18M

**Comment by kmiterror** [comment]
Then for some reason it failed on my machine. 
To a point that the log filled all the space available on /var/log
After reboot Rasp Pi was not able to bring up dhcp client service, I can only guess that something was trying to write log message and was not able.

After another reboot it booted up. I was able to open volumio web interface but still music was not playing. 
After some investigation (it took more than 1 minute ;) ) I figured that volumio log is taking all the space.  After removing "volumio.log" manually everything started to work right of the bat.

What I'm using is a standard R Pi installation of volumio image, without any modifications. 
I wasn't even trying connecting to ssh before this issue occurred.
Music is playing through it for about 10h every day and it haven't caused much issues until recently.
Any ideas why it happened? 
Perhaps the volumiologrotate service crashed and after reboot when /var/log was 100% full, volumiologrotate was not able to start (because previous services failed) and do it's job either?

**Comment by volumio** [comment]
This log rotation is a recent thing, done after 2.712, which version are you on?

**Comment by kmiterror** [comment]
How can I check volumio verion through ssh?

**Comment by volumio** [comment]
cat /etc/os-release

**Comment by kmiterror** [comment]
VOLUMIO_VERSION="2.712"

**Comment by volumio** [comment]
What seems strange to me is that it hangs on startup. Logs are written on RAM...

**Comment by kmiterror** [comment]
It's also possible that what was happening is not exactly how I described it. 

I wasn't seeing the screen of my RPi when boot issue occurred. 
I only saw that it hasn't showed up in router dhcp list. Once it booted I looked through the boot.log and only error I saw was the one about DHCP client not being able to start up (without much explanation why).

I also remember that I clicked reboot in the web ui. 
After not being able to connect to it, I rebooted it by unplugging power cable.
After that (or perhaps after 2 power cable reboots) I think it booted, but the /var/log was full.

**Comment by kmiterror** [comment]
I runed this command to check what services are running: `systemctl --full --type service --all`
It looks like volumiologrotate.service has some problems:

![image](https://user-images.githubusercontent.com/4394164/76289418-5f888900-62a9-11ea-8a44-0b828d97047b.png)


When checking status of service with `systemctl start volumiologrotate` I see this (seems to be in failed state since boot@12 days ago)
![image](https://user-images.githubusercontent.com/4394164/76289928-885d4e00-62aa-11ea-9014-65fe3024000c.png)


When I try to start it with `systemctl start volumiologrotate` I get this:

![image](https://user-images.githubusercontent.com/4394164/76289649-dfaeee80-62a9-11ea-870b-eafb76913a1f.png)

Still no idea how it's possible that the /var/log was full after a reboot. 
Is it possible that after a boot something was logging so extensively that it filled up the whole 20MB?

**Comment by volumio** [comment]
Could you start manually volumiologrotate and paste the output here?

sudo su
/bin/volumiologrotate

thanks

also paste the output of this

ls /var/log

**Comment by kmiterror** [comment]
I runned `sudo su /bin/volumiologrotate` but it gave me an error:
![image](https://user-images.githubusercontent.com/4394164/76405278-2e32ba80-6388-11ea-8cb7-4c506b12708d.png)

I also checked the /bin folder and it looks that volumiologrotate is not there at all ` ls -l /bin | grep volumio`:
![image](https://user-images.githubusercontent.com/4394164/76405343-473b6b80-6388-11ea-9a05-21bb41d2d557.png)


Result of `ls /var/log` (mind that the volumio logs are already rotated by the solution I proposed above):
![image](https://user-images.githubusercontent.com/4394164/76405454-6cc87500-6388-11ea-8a33-35df806c2ad0.png)

**Comment by volumio** [comment]
Then this explains why you are having this issue: the rotation service instead of removing eccess logs just saves them, quickly filling the 20MB. Furthermore it makes /var/log/ persistent (while it should be mounted on RAM)

**Comment by kmiterror** [comment]
Glad that we move forward, have you got any clue why `volumiologrotate` is not in the bin folder?
Is it possible that it's missing because upgrade process didn't include it?

**Comment by volumio** [comment]
My fault: volumiologrotate was not included...
https://github.com/volumio/Build/commit/ba22215fabbe766d668749499a1c25fcefd90f0a

**Comment by kmiterror** [comment]
Thanks for a quick fix. 
On a side note, does it make sense to keep logs in RAM?
Most people will try rebooting before creating issue.
If they would send you logs (using volumio web UI) you won't be able to see anything related to the bug.
Is it because of those common SD card  corruptions on Raspberry Pi?
Thanks

**Comment by volumio** [comment]
Yes we avoid disk writes as much as possible, as they corrupt SD Cards
