### ISSUE TITLE
 ADAU1701 DSP I²S audio driver support

### ISSUE THREAD

**Issue by RAV1962** [volumio/Build#406]
Please enable ADAU1701 DSP I²S audio driver support.
This will open up new opportunities for Volumio. For example, car audio.

**Comment by ashthespy** [comment]
The ADAU1701 doesn't require any specific extra kernel modules to work, you just require a device tree overlay to enable it.

That being said, Volumio uses the upstream raspberry pi kernel, so if there is an overlay file added to their tree, it should make it's way into Volumio automatically.
