### ISSUE TITLE
Invaild shairport-sync User and Group Setting

### ISSUE THREAD

**Issue by mobo27** [volumio/Build#407]
https://github.com/volumio/Build/blob/6f6a0a1e87d011d762c5171424872673e1b85a85/volumio/lib/systemd/system/shairport-sync.service#L11

which should use volumio for both User and Group since shairport-sync does not exists

**Comment by volumio** [comment]
But we do actually add the user... https://github.com/volumio/Build/blob/eb67d125f7642faf9993dc311e0bec30fd6d0266/scripts/volumioconfig.sh#L502

Any suggestion?

**Comment by mobo27** [comment]
Seems this issue will be only occurs while updating from old version of volumio image, let me close this issue.
