### ISSUE TITLE
Secure Boot Failed x86

### ISSUE THREAD

**Issue by Jack-Chronicle** [volumio/Build#422]
I flashed the image to an 8gb flash drive, and it said it was successful
However whenever I attempt to boot into it, I get an error screen with a big lock icon and a message stating that "Secure Boot Failed" and it doesn't load past it. Haven't even been able to set it up yet...

**Comment by gkkpch** [comment]
please don’t use github to report future user-side issues, use our community.volumio.org instead.
Solution: disable secure boot in the bios, we do not support it.
