### ISSUE TITLE
Cannot find Kernel Sources for X86?

### ISSUE THREAD

**Issue by DrCWO** [volumio/Build#423]
The link https://github.com/volumio/linux for the Kernel Sources of x86 System is broken.
Any idea where I can find the sources?
I need it because I have to compile a custom ALSA driver.

Thanks for the Support
Charly

**Comment by volumio** [comment]
@gkkpch could you please share the link of the kernel sources for x86?
thanks!

@DrCWO are you expert in alsa drivers? If yes, would you mind contacting us at info at volumio dot org ?

**Comment by gkkpch** [comment]
Could you tell us the source of this link, where did you get/find it?

**Comment by DrCWO** [comment]
Hi all,

you ask me if I am expert in ALSA-Drivers. My answer is NO.

BUT I play from volumio to an ALSA Loopback device and have some Issues I like to fix.

 

*	Loopback driver is limited (without reason) to 192k. Like to change this so MPD is not resampling any more
*	Like to have a nicer name of the driver displayed in Roon ( I use Roon plugin)
*	Need to disable the second full duplex card to show up in Roon
*	Have to fix an issue when samplerate is changed in the loopback driver

 

So not a complete new driver but some minor changes.

I am an experienced C-programmer so this task seems not be so difficult for me.

And after that maybe I am an expert ;-)

 

For this little project I appreciate your help with the kernel sources…

 

Thanks a lot

Charly

 

Von: Volumio <notifications@github.com> 
Gesendet: Mittwoch, 28. Oktober 2020 15:56
An: volumio/Build <Build@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [volumio/Build] Cannot find Kernel Sources for X86? (#423)

 

@gkkpch <https://github.com/gkkpch>  could you please share the link of the kernel sources for x86?
thanks!

@DrCWO <https://github.com/DrCWO>  are you expert in alsa drivers? If yes, would you mind contacting us at info at volumio dot org ?

**Comment by volumio** [comment]
@gkkpch can you share the X86 sources?

@DrCWO then let's stay in touch!

**Comment by gkkpch** [comment]
sorry, no support until you show me the source of the link that failed, sorry.
I need to know *exactly* which kernel version, anything else is not going to help anyone.

**Comment by DrCWO** [comment]
On this page the “X86” link is broken

https://github.com/volumio/Build

 

I use the image to download and it reports this:

Linux Volumio 3.18.25 #4 SMP Mon Feb 12 18:30:53 CET 2018 i686 GNU/Linux

 

Is there a newer version for x86 would appreciate that 

 

Best 

Charly

 

Von: Gé Koerkamp <notifications@github.com> 
Gesendet: Freitag, 13. November 2020 02:20
An: volumio/Build <Build@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [volumio/Build] Cannot find Kernel Sources for X86? (#423)

 

sorry, no support until you show me the source of the link that failed, sorry.
I need to know exactly which kernel version, anything else is not going to help anyone.

**Comment by ashthespy** [comment]
The x86 link in https://github.com/volumio/Build#sources points to a missing https://github.com/volumio/linux repo. 
It should instead probably point to https://github.com/volumio/platform-x86 
Where Gé has outlined the steps to grab the correct kernel sources 

```
wget https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.25.tar.xz
unzx linux-3.18.25.tar.xz
tar xvf linux-3.18.25.tar
cd linux-3.18.25
```

Hope that helps..

**Comment by volumio** [comment]
Thanks. Added correct reference to it in https://github.com/volumio/Build/commit/021f5e9116ec67046e3dafb10c7ed02f71d4255b

**Comment by DrCWO** [comment]
THX a lot :)

 

Von: Ash <notifications@github.com> 
Gesendet: Dienstag, 24. November 2020 12:32
An: volumio/Build <Build@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Mention <mention@noreply.github.com>
Betreff: Re: [volumio/Build] Cannot find Kernel Sources for X86? (#423)

 

The x86 link in https://github.com/volumio/Build#sources points to a missing https://github.com/volumio/linux repo.
It should instead probably point to https://github.com/volumio/platform-x86
Where Gé has outlined the steps to grab the correct kernel sources

wget https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.25.tar.xz
 
unzx linux-3.18.25.tar.xz
 
tar xvf linux-3.18.25.tar
 
cd linux-3.18.25
 

Hope that helps..
