### ISSUE TITLE
Raspberry Pi GPIO Permissions

### ISSUE THREAD

**Issue by dbrgn** [volumio/Build#424]
(I hope this is the proper repository for reporting this issue.)

As `volumio` user, I cannot access `/dev/gpiochip0`, even though I'm in the `gpio` group.

```
volumio@volumio:~$ cat /etc/group | grep gpio
gpio:x:998:volumio
volumio@volumio:~$ ls -la /dev/gpiochip*
crw------- 1 root root 254, 0 Nov  2 12:02 /dev/gpiochip0
crw------- 1 root root 254, 1 Nov  2 12:02 /dev/gpiochip1
crw------- 1 root root 254, 2 Nov  2 12:02 /dev/gpiochip2
```

According to the [library I'm using](https://docs.golemparts.com/rppal/0.11.2/rppal/gpio/), this should work:

![2020-11-02-135811_965x270_scrot](https://user-images.githubusercontent.com/105168/97870603-776abc80-1d13-11eb-90e5-208d11de3ec4.png)

Of course I can fix this myself, but it would be nice if the image would support these permissions out of the box :slightly_smiling_face:

**Comment by dbrgn** [comment]
Can be fixed by changing the following in `/etc/udev/rules.d/92-gpio.rules` (just add `GROUP="gpio"`):

```diff
-SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", PROGRAM="/bin/sh -c 'chown volumio:volumio /sys/class/gpio/export /sys/class/gpio/unexport ; chmod 220 /sys/class/gpio/export /sys/class/gpio/unexport'"
-SUBSYSTEM=="gpio", KERNEL=="gpio*", ACTION=="add", PROGRAM="/bin/sh -c 'chown volumio:volumio /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value ; chmod 660 /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value'"
+SUBSYSTEM=="gpio", KERNEL=="gpiochip*", GROUP="gpio", ACTION=="add", PROGRAM="/bin/sh -c 'chown volumio:volumio /sys/class/gpio/export /sys/class/gpio/unexport ; chmod 220 /sys/class/gpio/export /sys/class/gpio/unexport'"
+SUBSYSTEM=="gpio", KERNEL=="gpio*", GROUP="gpio", ACTION=="add", PROGRAM="/bin/sh -c 'chown volumio:volumio /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value ; chmod 660 /sys%p/active_low /sys%p/direction /sys%p/edge /sys%p/value'"
```

**Comment by macmpi** [comment]
Not sure [current build](https://github.com/volumio/Build/blob/master/scripts/raspberryconfig.sh#L230) uses latest of `raspberrypi-sys-mods` as that package is cached in own @volumio repo.
You may check if [latest rule](https://github.com/RPi-Distro/raspberrypi-sys-mods/commits/master/etc.armhf/udev/rules.d/99-com.rules) fixes your issue.

**Comment by ashthespy** [comment]
I believe http://archive.volumio.org/debian/ is just a mirror of archive.raspberrypi.org -- so packages are the same. :-) 
```
curl -s http://archive.raspberrypi.org/debian/dists/jessie/main/binary-armhf/Packages | grep 'Package: raspberrypi-sys-mods' -C 2
Description: Network configuration for the Raspberry Pi UI

Package: raspberrypi-sys-mods
Version: 20170519
Architecture: armhf
$ curl -s http://archive.volumio.org/debian/dists/jessie/main/binary-armhf/Packages | grep 'Package: raspberrypi-sys-mods' -C 2
Description: Network configuration for the Raspberry Pi UI

Package: raspberrypi-sys-mods
Version: 20170519
Architecture: armhf
```
