### ISSUE TITLE
empty locale settings on volumio2 image

### ISSUE THREAD

**Issue by FishTest** [volumio/Build#48]
volumio@volumio:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

According to the above settings ,i can't use below function in c++ program about multibyte character display..
----------
setlocale(LC_ALL,"en_GB.UTF-8"); or setlocale(LC_ALL,"");
size_t r = mbstowcs (wc, c, cSize);
----------
it will return -1,so I can't succeed in converting and displaying the metadata of the song,
Do you have a good solution?

jessie's locale settings:
pi@raspberrypi:~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by volumio** [comment]
You can set the default locale you need 

sudo locale-gen en_GB
sudo locale-gen en_GB.UTF-8

**Comment by FishTest** [comment]
thanks,but mbstowcs still get an error result.I'll try it later

**Comment by FishTest** [comment]
final solution
Method 1:config with dpkg-reconfigure
sudo dpkg-reconfigure locales
then select en_GB.UTF-8 UTF-8
Method 2:
sudo nano /etc/locale.gen
remove "#" before en_GB.UTF-8 UTF-8
then run
sudo locale-gen
