### ISSUE TITLE
X64 imgpart is too small

### ISSUE THREAD

**Issue by volumio** [volumio/Build#480]
@ashthespy 
We need to have a x64 imgpart of at least 3,5 GB 

Would adding IMAGE_END=3900 to https://github.com/volumio/Build/blob/volumioOS/recipes/devices/x86_amd64.sh do the trick?
Can you suggest and do a PR?

**Comment by gkkpch** [comment]
I can do this tomorrow, so @ashthespy can concentrate on the other things

**Comment by gkkpch** [comment]
Yes, for x86 we can go the the far end of the initial image size, nobody will be using a 4Gb usb stick other than for testing purposed.

**Comment by volumio** [comment]
Thanks!

**Comment by ashthespy** [comment]
> Would adding IMAGE_END=3900 to https://github.com/volumio/Build/blob/volumioOS/recipes/devices/x86_amd64.sh do the trick?

Indeed, but better to add it to the `x86.sh` "family" device. 
https://github.com/volumio/Build/blob/7e70a9a70ccd64d4428d7e4fd88b97d5d2d1a8ba/recipes/devices/families/x86.sh#L26-L31

**Comment by ashthespy** [comment]
Fixed with 6c529b3

**Comment by gkkpch** [comment]
The limit on BOOT_END may have to be raised a little: in case we are editing initrd there is hardly enough room to keep a copy.
Will take care of that

**Comment by gkkpch** [comment]
Something else we need to consider, the old x86 installations have different partition sizes.
Though I believe there should be no issues, we will need to test the OTA from old to new very carefully.
