### ISSUE TITLE
Add custom Shairport

### ISSUE THREAD

**Issue by volumio** [volumio/Build#481]
@volumio 
As done for upmpdcli, add : https://repo.volumio.org/?dir=Volumio2/Buster/CustomPackages/shairport-sync

IMPORTANT: 
- Don't forget to put the source code in same folder
- Make sure this is also solved https://github.com/volumio/Build/issues/479
- Test if we need to add further dependencies as done with https://github.com/volumio/Build/commit/7e70a9a70ccd64d4428d7e4fd88b97d5d2d1a8ba

**Comment by ashthespy** [comment]
Are they build differences b/w the [official Debian package?](https://packages.debian.org/buster/shairport-sync) or is this for availability?

**Comment by volumio** [comment]
3 reasons:
- Availability
- We might want to custom compile it (as we always did, now we use official debs just to go faster in this phase)
- We want version lock, as it can happen that packages get updated with breaking changes. So we want to test everything before bumping release

**Comment by ashthespy** [comment]
Got it!
For the long-term then would suggest looking at hosting a proper package repo with all custom Volumio packages, instead of the current file repo. 
That will then make life easier in managing versioning and dependencies. Will also let users update base/security packages from upstream Debian without breaking Volumio's custom bits. 

Something like [aptly](https://www.aptly.info/) or [pulp](https://pulpproject.org/) makes this quite smooth to setup. Something to consider in the future..

**Comment by volumio** [comment]
@ashthespy that was also my first choice (4 years ago) and I tried both aptly and repepro...
It generated a huge amount of side issues and in the end I dropped it preferring the solution of fetching and installing debs...
But yeah, somethign we can try again in the future

**Comment by ashthespy** [comment]
No I completely agree, K.I.S.S, and moreover if it ain't broke don't bother fixing it..  ;-)

**Comment by volumio** [comment]
Done with: https://github.com/volumio/Build/commit/372bdae0d8df9e9e5bf86bcc195d777db160ca1f

however, for some reasons the custom systemd service is not there in the image.. needs to be further investigated

**Comment by ashthespy** [comment]
> however, for some reasons the custom systemd service is not there in the image.. needs to be further investigated

No investigation required -- just copy in service file as mentioned back in https://github.com/volumio/Build/pull/484#issuecomment-777611820

**Comment by ashthespy** [comment]
Fixed with #489
