### ISSUE TITLE
Consider switching `node_modeuls` tarball to LZMA from Gzip

### ISSUE THREAD

**Issue by ashthespy** [volumio/Build#482]
The `node_modules` tarball(s) pulled in by the scripts from `http://repo.volumio.org/Volumio2/node_modules_*` are packaged using [gzip](https://github.com/volumio/Volumio2/blob/4c35e516cfaf9032b39cae08a2186413ba3fb436/utils/misc/pack-modules.sh#L8-L21). 
By switching to LZMA saving are in the magnitude of  17M -> 7.9M for ~30s longer compression time..
```
[ .. ] Cleaning modules [ 195M ]
Cleaning node modules in folder /volumio/node_modules
Pre-clean size is 145

3489 files removed, Post-clean size is 78

[ .. ] Cleaned modules [ 114M ]
[ .. ] Packing Modules to node_modules_x86_v14.15.4.tar.xz
[ .... ] Done packaging node_modules [ 46 sec ] 
[ .. ] Archive size [ 7.9M ]
[ .. ] Node modules bundle created [ 2:3 min ]
```
```
[ .. ] Cleaning modules [ 195M ]
Cleaning node modules in folder /volumio/node_modules
Pre-clean size is 145

3489 files removed, Post-clean size is 78

[ .. ] Cleaned modules [ 114M ]
[ .. ] Packing Modules to node_modules_x86-v14.15.4.tar.gz
[ .... ] Done packaging node_modules [ 18 sec ] 
[ .. ] Archive size [ 17M ]
[ .. ] Node modules bundle created [ 1:39 min ]
```

Given the number of build being run, we should do our part to reduce the wasteful traffic and make the world a better place ;-)

**Comment by volumio** [comment]
I agree but it's a nice to have, not a priority ;) 
We're keeping a great pace for the buster release so let's focus on the big picture, and later do the details ;)

**Comment by ashthespy** [comment]
No rush, just wanted to bring point it out.. 

PS: [Bullseye's soft-freeze](https://wiki.debian.org/DebianBullseye) is scheduled for tomorrow - unsure about the time line you have in mind for a Buster release, but maybe we should reconsider and go from Jessie -> Bullseye?
