### ISSUE TITLE
Volumio 3 Beta Testing issues

### ISSUE THREAD

**Issue by gkkpch** [volumio/Build#497]
This is a list of all reported issues from the Volumio 3 Beta testing.
Please let me know when any of them are solved.

Volumio 3 X86
- [ ] First boot issues on Intel Celeron  [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-x86/45242/4l)
- [ ] Similar issue, User also had to reboot [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-x86/45242/6)
- [X] installToDisk menuitem is not visible for x86_amd64 (and x86_i386)  [Link to fix Volumio2 repo](https://github.com/volumio/Volumio2/pull/2087) && [LInk to fix Build repo](https://github.com/volumio/Build/pull/501)

Volumio 3 RPi

- [ ] DSP settings for Allo Piano 2.1 [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/6)
- [ ] Qobuz dying, seems to happen at the end of a track [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/9)
- [ ] Qobuz, resume after pause causes tokens to be displayed instead of title (also happens with Tidal) [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/15)
- [ ] Qobuz, play next not working [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/16)
- [ ] Errors in mpd.log after reboot and before playing anything [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/19)
- [ ] Default mixer set to "Hardware" where it should be "none" [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/10)

Volumio 3 Asus Tinkerboard
- [X] installToDisk menuitem is not working on Tinkerboard. Fix see installToDisk x86 (missing dcfldd package) 

Volumio 3 General Issues

- [X] Error: ENOENT: no such file or directory, open ‘/sys/class/net/eth0/address’ [Link to post](https://community.volumio.org/t/volumio-3-buster-general-issues/45265/2) &&  [Link to fix PR](https://github.com/volumio/Volumio2/pull/2085)
- [ ] Weird resampling when playing webradio [Link to post](https://community.volumio.org/t/volumio-3-buster-general-issues/45265/3)
- [X] No Volumio webradio stations, known issue because of volumiobuster variant  [Link to post](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/5)

**Comment by xipmix** [comment]
Ge, what does it mean when an item  (No volumio webradio stations) is checked: that it's fixed? My humble suggestion - it would be good to link them to the fixing PR or when people start working the problem, make an issue and link to it from here.

**Comment by gkkpch** [comment]
The tick means we do not intend any action (in this case) or it has been fixed, link to a PR is a good suggestion. I'll add it.
The webradio thing is a bit annoying perhaps, but not major because we know it is caused by using a different build variant (volumiobuster instead of volumio).

On 28 Feb 2021, at 10:47, xipmix <notifications@github.com> wrote:

Ge, what does it mean when an item (No volumio webradio stations) is checked: that it's fixed? My humble suggestion - it would be good to link them to the fixing PR or when people start working the problem, make an issue and link to it from here.

**Comment by ashthespy** [comment]
Would also suggest we distinguish between problems and things that can be fixed here (from the Build scripts/rootfs/packages side) and issues that need to be fixed over in [`volumio/Volumio2`](https://github.com/volumio/Volumio2).
From a quick glance at the issues - most are things that need fixing from the nodejs side?

**Comment by gkkpch** [comment]
I agree, that most of the issues seem node.js specific and volumio/Build may not the ideal place to keep this summary. But it is easier for me, to have it one one single place and not split it up.

**Comment by rrakso** [comment]
Hi! After upgarding volumio (OTA update) it does not show the WEB UI. I got these errors:
```javascript
Failed to instantiate module volumio due to:
Error: [$injector:nomod] Module 'volumio' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
![image](https://user-images.githubusercontent.com/23143274/138474309-69901b63-9f54-4033-a308-1036f1407f43.png)

But the Spotify connect works fine, and it boots correctly:
```bash
Oct 22 16:34:07 ersmusic volumio[1347]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Oct 22 16:34:12 ersmusic volumio[1347]: error: MyVolumio Plugin failed to authenticate in a timely fashion
Oct 22 16:34:12 ersmusic volumio[1347]: info: Completed starting MyVolumio Plugin
Oct 22 16:34:12 ersmusic volumio[1347]: info: BOOT COMPLETED
Oct 22 16:34:12 ersmusic volumio[1347]:  [Metrics]  CommandRouter:  44s 199.97ms 
Oct 22 16:34:12 ersmusic volumio[1347]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Oct 22 16:34:17 ersmusic volumio[1347]: Playing WAVE '/volumio/app/startup.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
```

Anyone knows how can I fix it? I not (yet :grin:) an Angular expert..

#### EDIT:

Volumio is showing its UI, after I run the `volumio updater restorevolumio` command... 

(Found it here: https://github.com/volumio/Volumio2/issues/1629)

**Comment by gkkpch** [comment]
@rrakso Please do not post Volumio Beta testing issues on github.
The correct place for beta reports is  [Volumio 3 RC1 Open Beta Testing](https://community.volumio.org/t/volumio-3-rc1-open-beta-testing/50284). 
Read the Opening Post of that thread.

Quote:
*To report, please make sure you add the following info*
*- Device, Audio output*
*- Clear explanation on how to replicate the problem*
*- [Send a log](https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html) and paste the link in your post*

In your case, also add from which to which version you did the OTA.
Thank you

**Comment by volumio** [comment]
@rrakso you probably edited some file manually. 
Can you tell us what did you do? So it helps preventing that to happen.

Did you install some plugin or some custom Ui?
