### ISSUE TITLE
Shairport-sync status not updating in player 

### ISSUE THREAD

**Issue by tlmyasirs** [volumio/Build#506]
I have tried **airplay** in volumio `version 0.014` its working but volumio **player** is unawre of it. and in any version ( including stable release ) of volumio, the **api** is not getting **play / pause** status of airplay

**Comment by ashthespy** [comment]
This repo is tracking the Volumio Build system. 
For specific issues with Volumio, your better of at either the [forums](community.volumio.org/) or for more specific issues with the core [`volumio/Volumio2`](https://github.com/volumio/Volumio2) and the UI  [`volumio/Volumio2-UI`](https://github.com/volumio/Volumio2-UI).


PS: You are on an old version, use the [new images from the forum](https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/79)
