### ISSUE TITLE
errors for sudo ./build.sh -b -d cubietruck  -v 2.0 command

### ISSUE THREAD

**Issue by norrest** [volumio/Build#55]
```
root@debian:~/volumio/build# sudo ./build.sh -b -d cubietruck  -v 2.0
Build folder exist, cleaning it
mkdir: cannot create directory ‘build/-d’: File exists
./build.sh: line 101: multistrap: command not found
mount: mount point build/-d/root/dev does not exist
mount: mount point build/-d/root/proc does not exist
mount: mount point build/-d/root/sys does not exist
Cloning Volumio Node Backend
Cloning into 'build/-d/root/volumio'...
remote: Counting objects: 9233, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 9233 (delta 9), reused 0 (delta 0), pack-reused 9202
Receiving objects: 100% (9233/9233), 4.26 MiB | 749.00 KiB/s, done.
Resolving deltas: 100% (5438/5438), done.
Checking connectivity... done.
Cloning Volumio UI
Cloning into 'build/-d/root/volumio/http/www'...
remote: Counting objects: 84, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 84 (delta 0), reused 0 (delta 0), pack-reused 80
Unpacking objects: 100% (84/84), done.
Checking connectivity... done.
Adding information in os-release
./build.sh: line 129: build/-d/root/etc/os-release: No such file or directory
Base System Installed
cp: cannot create regular file 'build/-d/root/etc/mpd.conf': No such file or directory
Writing system information
./build.sh: line 142: build/-d/root/etc/os-release: No such file or directory
Unmounting Temp devices
umount: build/-d/root/dev: mountpoint not found
umount: build/-d/root/proc: mountpoint not found
umount: build/-d/root/sys: mountpoint not found
Copying Custom Volumio System Files
cp: cannot create regular file 'build/-d/root/etc/dhcp/dhclient.conf': No such file or directory
cp: cannot create regular file 'build/-d/root/etc/samba/smb.conf': No such file or directory
cp: cannot create regular file 'build/-d/root/etc/polkit-1/localauthority/50-local.d/50-mount-as-pi.pkla': No such file or directory
cp: cannot create regular file 'build/-d/root/etc/ssh/sshd_config': No such file or directory
cp: cannot create regular file 'build/-d/root/etc/systemd/journald.conf': No such file or directory
cp: target 'build/-d/root/etc/network' is not a directory
scripts/configure.sh: 63: scripts/configure.sh: cannot create build/-d/root/etc/wpa_supplicant/wpa_supplicant.conf: Directory nonexistent
chmod: cannot access 'build/-d/root/etc/wpa_supplicant/wpa_supplicant.conf': No such file or directory
Done Copying Custom Volumio System Files
```

**Comment by volumio** [comment]
You need to do:

sudo su
./build.sh -b arm -d cubietruck  -v 2.0

But I don't remember at which point the cubietruck support was on thigs script...

**Comment by norrest** [comment]
nevermind
`
Copying Custom Volumio System Files
Copying ARM related configuration files
cp: cannot create regular file 'build/arm/root/etc/apt/sources.list': No such file or directory
cp: cannot create regular file 'build/arm/root/etc/dhcp/dhclient.conf': No such file or directory
cp: cannot create regular file 'build/arm/root/etc/samba/smb.conf': No such file or directory
cp: cannot create regular file 'build/arm/root/etc/polkit-1/localauthority/50-local.d/50-mount-as-pi.pkla': No such file or directory
cp: cannot create regular file 'build/arm/root/etc/ssh/sshd_config': No such file or directory
cp: cannot create regular file 'build/arm/root/etc/systemd/journald.conf': No such file or directory
cp: target 'build/arm/root/etc/network' is not a directory
scripts/configure.sh: 63: scripts/configure.sh: cannot create build/arm/root/etc/wpa_supplicant/wpa_supplicant.conf: Directory nonexistent
chmod: cannot access 'build/arm/root/etc/wpa_supplicant/wpa_supplicant.conf': No such file or directory
`
i am already sudo

**Comment by norrest** [comment]
Also

**Comment by volumio** [comment]
is there a build folder ? if not create it

**Comment by norrest** [comment]
Also 
`multistrap: command not found`
U need to add this to Help and say what what u cannot create

**Comment by volumio** [comment]
Please make sure you isntall all dependencies stated in build.sh

**Comment by volumio** [comment]
I don't get your last post ... You can build with this script on any conventional computer, and the result will be an img file...

**Comment by norrest** [comment]
Many errors 

Reading package lists... Done
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-base.list:2
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-firmware.list:2
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-fs.list:2
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-net.list:2
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-spotify.list:2
W: Target Sources (main/source/Sources) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:2 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-utils.list:2
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-base.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-base.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-base.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-base.list:1
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-firmware.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-firmware.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-firmware.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-assets.list:1 and /root/volumio/volumio/build/build/arm/root/etc/apt/sources.list.d/multistrap-firmware.list:1
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /root/volumio/volumio/bu

root@debian:~/volumio/volumio/build# whoami
root


ls -all
total 64
drwxrwxrwx 8 root root  4096 Apr 29 12:16 .
drwxrwxrwx 3 root root  4096 Apr 29 12:10 ..
drwxr-xr-x 3 root root  4096 Apr 29 12:16 build
-rwxrwxrwx 1 root root  5806 Apr 29 12:14 build.sh
drwxrwxrwx 8 root root  4096 Apr 29 12:14 .git
-rwxrwxrwx 1 root root 18027 Apr 29 12:14 LICENSE
drwxrwxrwx 4 root root  4096 Apr 29 12:14 platforms
-rwxrwxrwx 1 root root   761 Apr 29 12:14 README.md
drwxrwxrwx 2 root root  4096 Apr 29 12:14 recipes
drwxrwxrwx 4 root root  4096 Apr 29 12:14 scripts
drwxrwxrwx 5 root root  4096 Apr 29 12:14 volumio


root@debian:~/volumio/volumio/build# uname -a
Linux debian 4.5.0-1-amd64 #1 SMP Debian 4.5.1-1 (2016-04-14) x86_64 GNU/Linux

**Comment by volumio** [comment]
Not critical errors...

**Comment by norrest** [comment]
```

Setting up samba (2:4.2.10+dfsg-0+deb8u2) ...
Adding group `sambashare' (GID 112) ...
Done.
[FAIL] Starting SMB/CIFS daemon: smbd failed!
invoke-rc.d: initscript smbd, action "start" failed.
dpkg: error processing package samba (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libfluidsynth1:armhf (1.1.6-2) ...
Setting up fuse (2.9.3-15+deb8u2) ...
update-initramfs: deferring update (trigger activated)

```
Can i install samba later?

**Comment by norrest** [comment]
/root/volumio/volumio/build/platforms/cuboxi/uboot 
u-boot.img - it is a result of procedure?

**Comment by norrest** [comment]
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
Adding information in os-release
Base System Installed
Writing system information
Unmounting Temp devices
Copying Custom Volumio System Files
Copying ARM related configuration files
Done Copying Custom Volumio System Files
root@debian:~/volumio/volumio/build#

**What to do next?
Where to find the desired image for recording on micro SD?**

root@debian:~/volumio/volumio/build# ls -all
total 64
drwxrwxrwx 8 root root  4096 Apr 29 12:16 .
drwxrwxrwx 3 root root  4096 Apr 29 12:10 ..
drwxr-xr-x 3 root root  4096 Apr 29 12:16 build
-rwxrwxrwx 1 root root  5806 Apr 29 12:14 build.sh
drwxrwxrwx 8 root root  4096 Apr 29 12:14 .git
-rwxrwxrwx 1 root root 18027 Apr 29 12:14 LICENSE
drwxrwxrwx 4 root root  4096 Apr 29 12:14 platforms
-rwxrwxrwx 1 root root   761 Apr 29 12:14 README.md
drwxrwxrwx 2 root root  4096 Apr 29 12:14 recipes
drwxrwxrwx 4 root root  4096 Apr 29 12:14 scripts
drwxrwxrwx 5 root root  4096 Apr 29 12:14 volumio

**Comment by gkkpch** [comment]
I think you are missing the point, without a build script for **cubietruck** you will NOT get an image.
That build script has not been done yet, so building stops after producing the arm rootfs.
