### ISSUE TITLE
Multistrap Broken on Ubuntu 14.04 (Affects Build)

### ISSUE THREAD

**Issue by maximus5684** [volumio/Build#60]
Just something you might want to note for other users in the Readme if they are building on Ubuntu 14.04. Multistrap is broken and fails with the following error:

Global symbol "$forceyes" requires explicit package name at /usr/sbin/multistrap line 989.
Execution of /usr/sbin/multistrap aborted due to compilation errors.

To fix this error, you just need to remove $forceyes from line 989 of /usr/sbin/multistrap. It's a known bug and has been fixed in newer versions. See https://bugs.launchpad.net/ubuntu/+source/multistrap/+bug/1313787

**Comment by gkkpch** [comment]
Hi, thanks for this info. I moved from Ubuntu to Debian last year, just because of that. Could have saved myself the trouble had I known it.
Another thing to watch out for, do not put your build directory on an nfs share. Get's you into trouble trying to start chroot/ qemu.

**Comment by gkkpch** [comment]
can be closed
