### ISSUE TITLE
building v2.0 on virtualBox is broken

### ISSUE THREAD

**Issue by noam1023** [volumio/Build#63]
1. disk size too small. I extended it with vboxmanage + gparted
2. many errors -- simply too many to quote here.

command used:
cd build
./build.sh -b arm -d pi -v 2.0

**Comment by gkkpch** [comment]
I don't know what you are doing, but we have used the build scripts successfully for ages. 
Nothing is broken, there is no such thing as "building v2.0 on VirtualBox". This is your responsibility, perhaps doing it in a way we have not foreseen. But from the two half sentences you supplied I  won't get far. If you want help, then please supply us with more info, I'm sure we get it working. So what OS platform are you on? Debian, Ubuntu? Versions? Did you install all prerequisites? Please supply the standard output, with "many erros -- simply too many to quote" we have to do "too many guesses", be more specific please..

**Comment by gkkpch** [comment]
This is what works:
- Windows 10, i7, 8Gb memory
- Virtual Box 5.0.20 with matching extension pack
- Debian Jessie 8.3 64bit
- Volumio prerequisites for arm platforms: git, build-essential (optional), squashfs-tools, kpartx, multistrap, qemu-user-static, samba, debootstrap, parted, dosfstools, qemu, binfmt-support
- your user added to sudoers (don't use root, that is bad praxis)
- login with your user
- clone http://github.com/volumio/Build
- change to Build folder
- execute: sudo ./build.sh -b arm -d pi -v 2.0
When done properly, you should not have any issues...

**Comment by noam1023** [comment]
Apologies for the partial post. I downloaded "VolumeioVM-VirtualBox.zip" to my Win 10.
Modified the VM network to NAT (so I can connect to internet) and ran with virtualBox 5.0.10.
This is the virtualBox Alpha5 image downloaded from https://github.com/volumio/Volumio2 .

I will retry with the Vmware image now.
I totally agree "don't use root".  why does build.sh demand using sudo?

PS: I recommend adding the version number to the zip file ( "VolumioVM-VirtualBox.alpha5.zip")
thanks!

**Comment by gkkpch** [comment]
No apologies necessary.
I think it would be easier to use Virtualbox with a new image from scratch. The alpha version is not up-to-date anymore anyway. Following my suggestion, you should be ok. Yes, takes a bit of work but will work..

**Comment by gkkpch** [comment]
Btw. I use Virtualbox with bridged adapter. Not sure if that is the correct way..

**Comment by gkkpch** [comment]
Why sudo? Because the scripts are using chroot/qemu..

**Comment by noam1023** [comment]
I used a clean install of Debian with 8GB disk (virtualbox), and installed the prerequisites manually.
This worked - at least the compilation completed

**Comment by gkkpch** [comment]
excellent! 
Just remember the x86 version is functional, but not complete yet, you're welcome to contribute if you can :)

**Comment by gkkpch** [comment]
@volumio: this one can be closed
