### ISSUE TITLE
Build x86 image on Debian 7

### ISSUE THREAD

**Issue by cron410** [volumio/Build#70]
`strip:build/x86/root/usr/sbin/update-initramfs: File format not recognized
strip:build/x86/root/usr/sbin/tarcat: File format not recognized
strip:build/x86/root/usr/sbin/update-fonts-dir: File format not recognized
strip:build/x86/root/usr/sbin/dpkg-reconfigure: File format not recognized
strip:build/x86/root/usr/sbin/pam-auth-update: File format not recognized
strip:build/x86/root/usr/sbin/update-rc.d: File format not recognized
strip:build/x86/root/usr/sbin/update-ca-certificates: File format not recognized
strip:build/x86/root/usr/sbin/grub-mkconfig: File format not recognized
strip:build/x86/root/usr/sbin/nfsiostat: File format not recognized
strip:build/x86/root/usr/sbin/service: File format not recognized
strip:build/x86/root/usr/sbin/mksmbpasswd: File format not recognized
strip:build/x86/root/usr/sbin/add-shell: File format not recognized
strip:build/x86/root/usr/sbin/invoke-rc.d: File format not recognized
strip:build/x86/root/usr/sbin/adduser: File format not recognized
strip:build/x86/root/usr/sbin/deluser: File format not recognized
strip:build/x86/root/usr/sbin/update-mime: File format not recognized
strip:build/x86/root/usr/sbin/pam_getenv: File format not recognized`

`Size after strip1.3G build/x86/root/`

Not sure how to fix this. Building the x86 image on Ubuntu 14.04 didnt work either. I basically followed the directions in readme.md but is there something else I have to do before running the build script? I really just want an x86 image to run on an old thin client. I can't find anywhere to download this image so I tried building it myself.

**Comment by volumio** [comment]
Those errors are not critical... X86 image is not ready yet, but the script works and you should get a working image...

**Comment by cron410** [comment]
Where is the image file? Should it be in the root of build/ ?

**Comment by gkkpch** [comment]
No, it is in the directory you cloned Build to and started ./build.sh. From the warnings you get, it seems you did not generate the image at all.
Make sure to issue ./build.sh -b x86 -d x86 -v 2.0 or run the 2nd part ( as you have to rottfs already) with ./build.sh -d x86 -v 2.0, where you put anything for <2.0>

**Comment by cron410** [comment]
I'm an idiot. I was using -b x86 -d all instead of -b x86 -d x86. I'll report back here with the outcome.

**Comment by gkkpch** [comment]
I think this one can be closed too after a few days. It's a handling error, not an issue.
Perhaps we should take the -all option out of the example too, as it is not working that way (yet) it just confuses.

**Comment by cron410** [comment]
Got it booted this morning. I'm having issues with networking, but I'll start another thread for that.

**Comment by gkkpch** [comment]
Yes, that is another issue we're working on. Problem is, that when you build yourself, you do that on your own risk in a still volatile environment at the moment, as we in between release candidates and releases. You could call yours a "nightly", unguaranteed. No use to create an issue for everything, unless it is just after an announced RC or fix. You can also follow gitter and report problems there. Test as much as you can and give us feedback,  much appreciated!

**Comment by cron410** [comment]
Not sure what you did, but ethernet is working for me on x86 now! I did a git pull and build. Worked perfectly. WLAN isnt important for me.
