### ISSUE TITLE
volumio.log

### ISSUE THREAD

**Issue by gkkpch** [volumio/Build#9]
Ok, coming back to the /var/log/volumio.log issue :)

It is good practise to keep /var/log to 0755, following might be a good alternative.
I suggest to put the following in fstab instead of the current /var/log line:

*tmpfs     /var/log               tmpfs   defaults,noatime,mode=0755				 0 0
tmpfs     /var/log/volumio  tmpfs   size=20M,nodev,uid=1000,mode=0777,gid=4,    0 0*

In case we do want to allow logging mpd, it could be in the volumio directory or like this:

*tmpfs     /var/log               tmpfs   defaults,noatime,mode=0755				 0 0
tmpfs     /var/log/volumio  tmpfs   size=20M,nodev,uid=1000,mode=0777,gid=4,    0 0
tmpfs     /var/log/mpd       tmpfs   size=20M,nodev,uid=\<uid-mpd\>,mode=0777,gid=\<gid-audio\>,    0 0*

This way */var/log* remains standard and the only thing that it needs is a small change in */volumio/app/index.js* and set the file paths to */var/log/***volumio/***volumio.log*. That's all.
Works on an Odroid C1, presumably on a PI too (can't test it, don't have one anymore).

**Comment by volumio** [comment]
Agree, will apply the changes...

**Comment by gkkpch** [comment]
Fine!
