### ISSUE TITLE
/var/log/samba missing because /var/log is overlaid with a tmpfs

### ISSUE THREAD

**Issue by xipmix** [volumio/Build#93]
I noticed a lot of complaints from samba-related daemons that /var/log/samba is missing. firststart.service creates it, and it exists in the fully-booted system on the first boot.

But on subsequent boots the /var/log entry in /etc/fstab 

```
tmpfs   /var/log                tmpfs   nodev,uid=1000,mode=0777,gid=4, 0 0
```

overlays what is in the distributed image with an empty tmpfs filesystem.

I can umount the tmpfs and underneath is all the expected /var/log structure. So I wonder if what is meant here is:

```
tmpfs   /var/log/volumio                tmpfs   nodev,uid=1000,mode=0777,gid=4, 0 0
```

i.e. reserve a special directory, owned by the volumio user, for the volumio app's log. Changing this would also require fixing the path used in /app/index.js.

Otherwise, perhaps  /var/log/samba should be created on every boot, perhaps as another tmpfs

```
tmpfs   /var/log/samba         tmpfs   defaults,nodev,noatime,mode=0755 0 0
```

Attached is a zip showing the first and second boots of a fresh 2.001, with the contents of /var/log once the system is fully started up.
[firsttwoboots.zip](https://github.com/volumio/Build/files/541441/firsttwoboots.zip)

**Comment by macmpi** [comment]
Yes have similar issue here opening ssh sessions:
`Oct 27 14:34:13 volumio sshd[1379]: pam_env(sshd:session): Unable to open env file: /etc/default/locale: No such file or directory
Oct 27 14:34:13 volumio sshd[1379]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Oct 27 14:34:14 volumio sshd[1379]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
`

**Comment by volumio** [comment]
The intention is write all logs to ram, in order to prevent sd card corruption. 
At this poin I think we should add to fstab every log entry for complaining services... 
What do you think?

**Comment by xipmix** [comment]
Thanks for clarifying. In that case it makes sense to add more fstab entries for different log dirs. A brief comment fstab about why they are there might be useful. However if some logs are going to be written by root and some by other users, I think it is worth keeping the non-root ones in separate /var/log subdirectories that can be set up with the right owner and permissions.

**Comment by volumio** [comment]
Maybe we could create a service that creates those temp dirs with appropriate permissions... 
At the end of the build process we could dump the content of /var/log and put those on a script... But maybe it gets too complicated...

**Comment by xipmix** [comment]
On Thu, Oct 27, 2016 at 04:07:17PM -0700, Volumio wrote:
> At the end of the build process we could dump the content of
> /var/log and put those on a script...  But maybe it gets too
> complicated...

I think this could work, something like
```
find /var/log -maxdepth 1 -type d ! -uid 0 | sort | \
while read d
do
    gid=`stat -c %g $d`
    uid=`stat -c %u $d`
    echo "tmpfs $d tmpfs nodev,uid=$uid,gid=$gid,mode=0775 0 0" >> /etc/fstab
done
```

**Comment by macmpi** [comment]
will that work with logs eventually generated by plugins?
Hopefully we won't be filling-out RAM with logs (some devices only have 512MB) ;)

**Comment by xipmix** [comment]
Interesting question. There are limits on the tmpfs size, it looks like it has been set to 20% of virtual memory (/etc/default/tmpfs). Every time you reboot the logs will be zeroed. For long-running machines log rotation should in principle take care of removing logs before things get too full, but with 0.5Gb to work with some tuning might be needed.

**Comment by xipmix** [comment]
I tried this out on a 2.009 image. Stop volumio, unmount existing /var/log. The script I tried and results shown below.

```
find /var/log -maxdepth 1 -type d | sort | \
while read d
do
    gid=`stat -c %g "$d"`
    uid=`stat -c %u "$d"`
    # Don't override any existing entries.
    # The spaces avoid matching a substring, ie a parent dir
    grep -q -F " $d " /etc/fstab && continue
    if [ "0" = "$uid" ] && [ "0" = "$gid" ]; then
        echo "tmpfs  $d  tmpfs  nodev,defaults 0 0"
    else
        echo "tmpfs  $d  tmpfs  nodev,uid=$uid,gid=$gid,mode=775 0 0"
    fi
done
```
Result
```
tmpfs  /var/log/apt  tmpfs  nodev,defaults 0 0
tmpfs  /var/log/fsck  tmpfs  nodev,defaults 0 0
tmpfs  /var/log/mpd  tmpfs  nodev,uid=110,gid=29,mode=775 0 0
tmpfs  /var/log/ntpstats  tmpfs  nodev,uid=100,gid=103,mode=775 0 0
tmpfs  /var/log/samba  tmpfs  nodev,uid=0,gid=4,mode=775 0 0
```

This is _maybe_ sane enough to continue considering this approach. Would need /var/log/volumio as well. I notice that most systems (all but rpi?) set a limit of 20M on /var/log as a whole, but that could be worked in I guess.

Does not handle the /var/spool entries (cups and whatnot) but presumably those are always going to be handmade additions to the *config.sh scripts?

**Comment by volumio** [comment]
That's a great approach. We can edit the volumio.log entry, no problem at all. And yes, we will need to set /var/log max size to 20 megs , additionally it would be great to find a way to delete the logs when we hit max size (wathdog? systemd service?)

I think that the above script could be a systemd service that gets enabled just before volumio starts. What do you think?

**Comment by xipmix** [comment]
This sounds like it should work and it nicely extends what firststart.service is doing now. /var/log could still be set up as now, in the *config.sh (but owned by root:root). That satisfies the need to limit the size. The other log areas could be setup as subdirectories on that tmpfs by a systemd service that runs on each boot strictly before firststart does.

We would need a way of knowing which directories to create with what permissions, across boots. Instead of unmounting and ferreting about in the underlying /var/log, it might be better to have the build script put a tar file in /etc which contains the (empty) /var/log subdirectories that are required and have the systemd service unpack that into the clean /var/log tmpfs.

Regarding plugin logs. Would it be simplest if they all logged to /var/log/volumio/<plugin>.log? Or do they already end up logging to volumio.log?

To keep the log sizes under control, I think logrotate should be given a chance to prove it can handle the task. For the volumio logs I think a daily rotation that keeps just one compressed log around should do it. 
```
/var/log/volumio/*.log
{
  rotate 1
  daily
  compress
  missingok
  notifempty
  create 0644 volumio volumio
}
```

**Comment by volumio** [comment]
I'm not sure about the firststart strategy, this gets called at the first boot..
As for the volumio.log we can move it without issues...

**Comment by xipmix** [comment]
On Sun, Oct 30, 2016 at 04:22:48AM -0700, Volumio wrote:
> I'm not sure about the firststart strategy, this gets called at
> the first boot..

This is tricky to explain concisely. I wasn't suggesting to exactly
replicate 'firststart'. Rather that the new unit would start just
before 'firststart' on the first boot and on subsequent boots it
would start at about the same time as it did on the first, relative
to the other units. Since firststart gets disabled once it has run
once, I guess we can't use it for a Before directive in the unit file.

Perhaps a better way to express what is wanted is that the new unit
should run immediately after local-fs.target? We want it to be done
before any daemons that want to use the new subdirs try to start.
